### ISSUE TITLE
Cloud Speech-to-Text API C++ (beta version)

### ISSUE THREAD

**Issue by gauravG2021** [googleapis/google-cloud-cpp#10285]
Hi,
we want to replace the c++ STT libraries of previous vendor with google stt client library.
I have like below questions:-

1. Are the Cloud Speech-to-Text API C++ libraries are  comerciallly stable?
2. Cloud Speech-to-Text API C++ i see at few places as being referd as experminetal or beta version?
3. does it permorfm STT on AMR-WB codes?

**Comment by dbolduc** [comment]
> 1. Are the Cloud Speech-to-Text API C++ libraries commercially stable?

Yes, the C++ client library is commercially stable...

> 2. Cloud Speech-to-Text API C++ I see at few places as being referred as experimental or beta version?

...but as you point out it, the library contains some experimental APIs.

**Experimental Speech-to-Text v2 client:**
The library has a `google::cloud::speech_v2::SpeechClient`, which is experimental, because the service, [Cloud Speech-to-Text v2](https://cloud.google.com/speech-to-text/v2/docs), is pre-GA (not commercially stable).

I recommend using the v1 service, unless you need some feature that is only available in v2. The client for the v1 service is: `google::cloud::speech::SpeechClient` (which is used in the [quickstart](https://github.com/googleapis/google-cloud-cpp/tree/main/google/cloud/speech/quickstart) and [samples](https://github.com/GoogleCloudPlatform/cpp-samples/tree/main/speech/api)).

**Experimental `AsyncStreamingRecognize` ([bidirectional streaming RPC](https://grpc.io/docs/what-is-grpc/core-concepts/#bidirectional-streaming-rpc)):**
The v1 client has an API that is marked as experimental.
https://github.com/googleapis/google-cloud-cpp/blob/94285ba95685b3ad277fd094bfdae15f0e43fe40/google/cloud/speech/speech_client.h#L202-L205

It is marked as experimental, because the API is a little tricky to use. We do have samples that demonstrate how to use the API. (The `streaming_transcribe*.cc` programs show how to properly call `AsyncStreamingRecognize`): https://github.com/GoogleCloudPlatform/cpp-samples/tree/main/speech/api

> 3. does it perform STT on AMR-WB codes?

According to these docs, yes. https://cloud.google.com/speech-to-text/docs/encoding#audio-encodings

**Comment by coryan** [comment]
Seems like this is answered. If there is are follow up questions please reopen or create a discussion item.
