### ISSUE TITLE
Refactor TimerQueue kMaxSleep

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#10522]
Determine if there is a better value for kMaxSleep or if we need to remove the mechanism entirely in favor of some sort of wait call to the condition variable.

**Comment by devbww** [comment]
See https://github.com/googleapis/google-cloud-cpp/issues/10521#issuecomment-1376157202 for an example of avoiding `kMaxSleep`.

A small point otherwise, was just the name: a service thread will happily sleep for a duration longer than `kMaxSleep` if you schedule such a timer, so in what sense is it a "max".  It is really the amount of time we sleep when we have no other deadlines.  We might as well use `std::chrono::system_clock::max()` in that case, and avoid another need for `now()`.
