### ISSUE TITLE
Submit bigtable::chrono_literals to abseil.io for consideration

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#109]
The user-defined literals are generally useful for tests.  One may not want them exposed in the general interface of a library, but they make the tests more readable.

**Comment by devjgm** [comment]
Rather than contribute these to Abseil, we might want to reconsider our use of the chrono_literals. While there's no question that `123_us` reads better than `microseconds(123)`, there's a cost associated with using these non-standard (i.e., not from std::chrono) literals. The costs that I see are:

1. Requires another `#include` / dep
2. Requires the use of a using *directive*, which [is not advised](https://abseil.io/tips/153) for a variety of reasons... **OR**
3. Requires strange-looking and verbose using declarations, like `using ::google::cloud::testing_utils::chrono_literals::operator"" _ms;` (NOTE: The space before the underscore is *required* in gcc 4.8).

For example:

```cc
using ::google::cloud::testing_util::chrono_literals::operator"" _ms;
using ::google::cloud::testing_util::chrono_literals::operator"" _us;
...
  Foo(123_ms + 456_us);
```

The alternative is

1. Include `<chrono>`, which should be included anyway if you're using durations.
2. Normal/short using declarations.
3. In C++14, we *could* use a using *directive* as is advised by the C++ standard, which is akin to pulling those literals into the global namespace, but that may an exception to the rule since it's advised by the C++ standard. ??? Dunno. We'll decide that when we can use C++14.

For example:

```cc
using ::std::chrono::milliseconds;
using ::std::chrono::microseconds;
...
  Foo(milliseconds(123) + microseconds(456));
```
I think I have a *slight* preference for directly using chrono rather than our own custom literals, *BUT* I could easily be convinced to keep our chrono literals because of the succinct call sites they enable.

I'd really like to hear others' thoughts.

Summons @coryan @devbww

**Comment by coryan** [comment]
Removing the user-defined literals in favor of `using ::std::chrono::{milliseconds,microseconds};`  is fine I guess. Or if we are desperate for horizontal space (and the scope is small enough):

```C++
using ms = ::std::chrono::milliseconds;
using us = ::std::chrono::microseconds;
...
Foo(ms(123) + us(456));
```

I will miss the C++14 chrono literals, but that is not the only thing I will miss from C++14.

----

Having said that (and note that I am fine with removing these suffix operators):

> 3\. Requires strange-looking and verbose using declarations, like `using ::google::cloud::testing_utils::chrono_literals::operator"" _ms;`

We could make an exception against the rule for using directives, as: 

* the `::google::cloud::testing_utils::chrono_literals` namespace just has these symbols, and
* the common ancestor is (for most of our code) is `::google::cloud`, so thing are less dire than usual.

I am 😐 on my own argument here.

**Comment by devbww** [comment]
When we have Abseil, will we eschew chrono?

**Comment by coryan** [comment]
> When we have Abseil, will we eschew chrono?

I do not believe we should.  We need to make it easy to use our libraries.  We should use abstractions that most C++ developers are familiar with. `std::chrono` is part of the standard, the application developers will be familiar with it (warts and all), introducing new types is just one more thing for them to learn as they are trying to learn Bigtable, or GCS, or Spanner.

**Comment by devjgm** [comment]
I agree with @coryan. I do think we should continue using chrono in public interfaces. This will make the library easy for users who already know chrono. However, internally, we may decide to use `absl::Time`, because it has more useful features than the C++11 version of chrono.

**Comment by coryan** [comment]
I am closing this because I doubt we will get the operators submitted to Abseil, and there is nothing actionable left in this bug.
