### ISSUE TITLE
Some spanner instances do not support DataBoost?

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11201]
I just got this in a PR.  Since we pick the spanner instances at random it may not affect all builds:

```
Step #3: 2023-04-07T15:02:53.975881932Z [DEBUG] <139635551693376> Finish() >> PERMISSION_DENIED: This instance (projects/cloud-cpp-testing-resources/instances/test-instance-15) is not allowed to use DataBoost at this time. Please contact cloud-spanner-sa-preview@google.com for more information. (google/cloud/spanner/internal/logging_result_set_reader.cc:53)
```

* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/1f352100-6781-4147-bf9d-97b97d389703;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/11200/7db9ef34c2689c9e65f3ab392fbe2468b23c2bdc/fedora-37-cmake-integration-production/log-1f352100-6781-4147-bf9d-97b97d389703.txt

**Comment by devbww** [comment]
It turns out that currently:
1. Spanner instances have to be allow-listed to use DataBoost, and
2. not all regions have "DataBoost OA capacity".

All our _"test-instance-**N**"_ instances have been allow listed, but the _"labels.samples:yes"_ subset are all in us-east1, which does not have capacity.

Given that we can't even discern a difference between DataBoost on and off, it doesn't seem worth it to temporarily shift instances/labels around.  Instead, I'll re-enable the samples but with an allowance for kPermissionDenied ... then they will start working whenever DataBoost is generally available.  Finally, we can remove the allowance any time after that.
