### ISSUE TITLE
Consider using propagator API for `X-Cloud-Trace-Context`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11355]
This is progress, but I suspect we would rather use OpenTelemetry's propagator API.

We would define the cloud trace context propagator, and ensure it is used by `InjectTraceContext`.

Maybe just open an issue like `Consider using OpenTelemetry's Propagator API for "X-Cloud-Trace-Context" injection`.

_Originally posted by @dbolduc in https://github.com/googleapis/google-cloud-cpp/pull/11352#pullrequestreview-1396348901_

**Comment by dbolduc** [comment]
If we want to be a goody-two-shoes and use OpenTelemetry's Propagator API, we would have to make a CloudTraceContext textmap propagator. It would look a lot like:

https://github.com/dbolduc/google-cloud-cpp/blob/b65a2fc5ab85850319d0d768a475b13e24326b4e/google/cloud/internal/open_telemetry.cc#L59-L103

Some notes:

- Terminating the `string_view` with a `\0` was not necessary. I was creating a `std::string{sv}` instead of a `std::string{sv.data(), sv.size()}`, later in the code. :monkey: 

- Internally, Google does not want to keep using the `X-Cloud-Trace-Context` header. I have been told that the w3 trace context format is at parity with `X-Cloud-Trace-Context`.... but I think they were lying. All this to say, we still need to use this header, but we should not make a Cloud Trace Context propagator public.

**Comment by alevenberg** [comment]
I think we can break this down into 

- [ ] Create a TextMapCarrier that holds the headers for the `RestContext`
- [ ] Create a custom `opentelemetry::context::propagation::GlobalTextMapPropagator` called `CloudTraceContext` that encodes the field
- [ ] Use the OTel API instead of setting the headers [here](https://github.com/coryan/google-cloud-cpp/blob/81874e0c57e663234d3d8ea67804c451d331757f/google/cloud/internal/tracing_rest_client.cc#L53-L56)
