### ISSUE TITLE
[Flake] storage FAILED_PRECONDITION in InsertObjectMedia

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#11839]
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/43ab4c8097adea76ca0c552dded6bb353a67d56e/fedora-msan-msan/log-43201aba-9d5c-4623-b589-661e1ca5c02c.txt

Multiple storage integration tests failed with FAILED_PRECONDITION in InsertObjectMedia calls.

**Comment by coryan** [comment]
FYI, we are trying to track all bugs related to integration tests being flaky in #10413

I think the FAILED_PRECONDITIONS are a consequence of the initial UNAVAILABLE errors.  The request succeeded but it was retried because it is idempotent.  It is idempotent because it has a "if does not exist already" pre-condition.  The retry fails because the first request was successful (the message sneaked through) and the object now exists.  Hilarious (not).

The test should probably handle FAILED_PRECONDITION or ALREADY_EXISTS and just get the metadata.

There is a feature request (b/280808412) to address this.  Seems like it is time to implement it.

**Comment by coryan** [comment]
90d without repeats. Closing.
