### ISSUE TITLE
Push data to bigquery without having the protobuf schema

### ISSUE THREAD

**Issue by Yusup-Badiev** [googleapis/google-cloud-cpp#12284]
**What component of `google-cloud-cpp` is this feature request for?**
`google/cloud/storage`

**Is your feature request related to a problem? Please describe.**
I am trying to create a proxy that redirects pushes to bigquery but I am running into the problem
that in order to push to bigquery you need to have a local protobuf schema defined in a file. But 
I assume that bigquery has this schema so why do I have to define the schema in the request why 
can't I just send the data as a json object? and leave the schema data in the `AppendRowsRequest.proto_rows.writer_schema.proto_descriptor` empty. (I might be 
wrong and that may be another way of writing to bigquery that does not include having 
local proto file and populating `AppendRowsRequest.proto_rows.writer_schema.proto_descriptor` with a schema
 if so please let me know)

**Describe the solution you'd like**
I would like to send data as json like the java library allows with the JsonStreamWriter and not have to 
have a local protobuf file and still be able to get data into bigquery

**Describe alternatives you've considered**
I have considered retrieving the schema for bigquery and then using that to as a the schema but bigquery
only seems to provide the schema in json and so that would envolve compile a json schema to protobuf,
generated the protobuf code and then linking it at run time which seems like a lot of effort. (when I say bigquery
only provides it in json I mean the schema retrieve from `AppendRowsResponse->avro_schema().schema()`)

**Comment by coryan** [comment]
> What component of google-cloud-cpp is this feature request for?
> `google/cloud/storage`

 Your question seems to be about `BigQuery` and that lives in `google/cloud/bigquery`.  I am going to assume that you are trying to use the BigQuery Storage API at `google/cloud/bigquery/storage`, please correct me if I am wrong.

> But I assume that bigquery has this schema so why do I have to define the schema in the request why
can't I just send the data as a json object?

I don't know, and there is little we can do in the C++ client library to fix this problem.  This is currently a requirement in the API for the BigQuery Storage API:

https://cloud.google.com/bigquery/docs/write-api#api_details

https://github.com/googleapis/googleapis/blob/addc8bf656b67e4ea030c8d19624670568dd985f/google/cloud/bigquery/storage/v1/protobuf.proto#L42-L48

Your question (or variants of it) seems to be relatively common, you can find similar feature requests in the public issue tracker:

https://issuetracker.google.com/savedsearches/559654

Please consider opening a new request there, or adding your voice to an existing request.

BigQuery does have (as your probably know) APIs to insert data in proto format, but the C++ SDK does not (currently) supports them.

> I have considered retrieving the schema for bigquery and then using that to as a the schema but bigquery
only seems to provide the schema in json and so that would envolve compile a json schema to protobuf,
generated the protobuf code and then linking it at run time which seems like a lot of effort.

I am not sure how practical this is, but you could try to import the `.proto` file and then use dynamic messages:

https://protobuf.dev/reference/cpp/api-docs/google.protobuf.compiler.importer/#Importer
https://protobuf.dev/reference/cpp/api-docs/google.protobuf.dynamic_message/

Some people report success with this idea:

https://stackoverflow.com/questions/11996557/how-to-dynamically-build-a-new-protobuf-from-a-set-of-already-defined-descriptor

**Comment by coryan** [comment]
Closing.  The feature request belongs (and already exists) in the service [BigQuery issuetracker](https://issuetracker.google.com/savedsearches/559654).
