### ISSUE TITLE
flake: coverage-ci build failing due to "no valid records found in tracefile"

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#12710]
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/35e970cc2dbff24bf3d66dd669a345529cae7031/fedora-37-bazel-coverage/log-e7772137-123e-4b21-acc1-0cabeb38af1e.txt

`lcov: ERROR: no valid records found in tracefile /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/async_client_integration_test-grpc-media/test_attempts/coverage.dat`

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/0cba02571f84c25a3ed0ab9f1fc8511e542b5045/fedora-37-bazel-coverage/log-9aa56942-8465-4053-b1d4-b0ea99fde929.txt

`lcov: ERROR: no valid records found in tracefile /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/async_client_integration_test-default/test_attempts/coverage.dat`

**Comment by coryan** [comment]
If it is in the same file each time, maybe the program is crashing before it can leave any records.  This integration test is not affected by the `-default` vs. `-grpc-media` configuration.

**Comment by scotthart** [comment]
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/3e75f09421a11886a34b42a085fb1bda2da2df39/fedora-37-bazel-coverage/log-899ab065-3886-467a-a469-001c88aca681.txt

`lcov: ERROR: no valid records found in tracefile /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/async_client_integration_test-default/test_attempts/coverage.dat`

**Comment by coryan** [comment]
Ugh...  I just noticed this:

```
FAIL: //google/cloud/storage/tests:async_client_integration_test-default (see /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/async_client_integration_test-default/test_attempts/attempt_1.log)
```

Around line 4754 in:

* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/899ab065-3886-467a-a469-001c88aca681;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/3e75f09421a11886a34b42a085fb1bda2da2df39/fedora-37-bazel-coverage/log-899ab065-3886-467a-a469-001c88aca681.txt


We have configured Bazel to run tests 3 times.  That is hiding a flake in this integration test.  The documentation for `bazel coverage` is confusing:

https://bazel.build/configure/coverage#running_coverage

"Coverage reports are also produced if tests fail, though note that this does not extend to the failed tests - **only passing tests are reported.**"

I think that means the coverage report is empty for failed and flaky tests.  The log seems to support that:

```
FLAKY: //google/cloud/storage/tests:async_client_integration_test-default (Summary)
      /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/async_client_integration_test-default/test_attempts/attempt_1.log
      /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/async_client_integration_test-default/test_attempts/attempt_2.log
INFO: From Testing //google/cloud/storage/tests:async_client_integration_test-default:
==================== Test output for //google/cloud/storage/tests:async_client_integration_test-default:
Running main() from gmock_main.cc
Note: Randomizing tests' orders with a seed of 86806 .
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from AsyncClientIntegrationTest
[ RUN      ] AsyncClientIntegrationTest.ComposeObject
[       OK ] AsyncClientIntegrationTest.ComposeObject (360 ms)
[ RUN      ] AsyncClientIntegrationTest.ObjectCRUD
[       OK ] AsyncClientIntegrationTest.ObjectCRUD (271 ms)
[ RUN      ] AsyncClientIntegrationTest.StreamingRead
external/bazel_tools/tools/test/collect_coverage.sh: line 166:    20 Killed                  "$@"
--
Coverage runner: Not collecting coverage for failed test.
The following commands failed with status 137
```


Note the comment at the end.

The failures may be because the test is rather long.  I am going to shorten the integration test to see if that improves things.

**Comment by coryan** [comment]
This is a bug in the new `AsyncClient`.  Around here:

https://github.com/googleapis/google-cloud-cpp/blob/53822901fca94c127514f8bce6786eb8e313363d/google/cloud/storage/internal/async/insert_object.cc#L87-L93
