### ISSUE TITLE
Storage: Object write stream 410 Gone

### ISSUE THREAD

**Issue by eneloop2** [googleapis/google-cloud-cpp#12942]
Please see https://github.com/googleapis/google-cloud-cpp/issues/2894

What is the recommended way to handle this issue with an ObjectWriteStream? I have a pattern where I call stream.Close() in some destructor. I then inspect the metadata of the stream by calling stream.metadata(). The content of the metadata says that the code is NOT_FOUND with mesage Permanent error UploadChunk: Gone.

I suppose I need some way to hold a parallel buffer to the object write stream's internal `buf_` which will let me know where to continue writing.

**Comment by coryan** [comment]
> What is the recommended way to handle this issue with an `ObjectWriteStream`?

First, I am sorry you are affected by this problem. 

Second, there is no way to handle this issue in the library.  The problem is in the storage service. The client library should not attempt to recover from this, because  "410 Gone" is an authoritative response from the service indicating data loss.  If the server is working correctly the response indicates that trying again *will* fail.

Third, there are fixes for this server-side problem rolling out as I write this, but I am not at liberty to discuss further.  Please contact support if you need more information.  Refer them to https://issuetracker.google.com/issues/137168102?pli=1 and b/267487463 if needed.

> I have a pattern where I call `stream.Close()` in some destructor. I then inspect the metadata of the stream by calling `stream.metadata()`. The content of the metadata says that the code is `NOT_FOUND` with message `Permanent error 
UploadChunk: Gone`.

Ack.

> I suppose I need some way to hold a parallel buffer to the object write stream's internal `buf_` which will let me know where to continue writing?

You try something along these lines:

* save the [resumable_session_id()](https://cloud.google.com/cpp/docs/reference/storage/latest/classgoogle_1_1cloud_1_1storage_1_1ObjectWriteStream#classgoogle_1_1cloud_1_1storage_1_1ObjectWriteStream_1ad76cbfb93dd75acac9ef4d1b459e5d9b)
* start a new upload with the [UseResumableUploadSession](https://cloud.google.com/cpp/docs/reference/storage/latest/structgoogle_1_1cloud_1_1storage_1_1UseResumableUploadSession) option set to that value
* then query the status of the upload in the new object, including the [next_expected_byte()](https://cloud.google.com/cpp/docs/reference/storage/latest/classgoogle_1_1cloud_1_1storage_1_1ObjectWriteStream#classgoogle_1_1cloud_1_1storage_1_1ObjectWriteStream_1a92786274e00b9f3a4801c409ca8ae9cc)

And then try to rewrite from that point.

If your data source is persistent: say a file, as opposed to a stream of data generated on the fly, you can restart the upload from the beginning.
