### ISSUE TITLE
Modify generator stub factory function creation to call `DetermineServiceEndpoint`, check for failure, and create appropriate Error Auth/Credentials type when failure occurs (REST transport)

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#13303]

**Comment by dbolduc** [comment]
REST layers use `PopulateCommonOptions`, so this was fixed by #13334 

https://github.com/googleapis/google-cloud-cpp/blob/07a1fc5a59357cea32beb4aaef3db66aae8c1bf0/google/cloud/compute/accelerator_types/v1/accelerator_types_rest_connection.cc#L42-L44

https://github.com/googleapis/google-cloud-cpp/blob/07a1fc5a59357cea32beb4aaef3db66aae8c1bf0/google/cloud/compute/accelerator_types/v1/internal/accelerator_types_option_defaults.cc#L35-L38
