### ISSUE TITLE
Pubsub should use global propagator, not hardcoded one.

### ISSUE THREAD

**Issue by alevenberg** [googleapis/google-cloud-cpp#13307]
Add any context about the cleanup here.

**Comment by dbolduc** [comment]
We discussed this internally, and have not found a compelling reason to use a custom propagator.

If an application needs to extract context from a pubsub message, we will probably have to expose our own API to help them. Because we will control both ends, we should just stick to one format. Applications should not be bothered to set the propagators.

An application that wants tracing without injecting the trace context in a message seems not worth considering. At worst, we include an extra few bytes of junk in the message. I am no Pub/Sub expert, but it seems harmless to me.
