### ISSUE TITLE
Retrofit some test for AsyncOperation cancellation.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1387]
There are tests for individual classes inheriting from `AsyncOperation`, but there are none for the the `noex::Table` operations.

There should also be some integration tests for cancellation - we've made assumptions on how gRPC reports cancellation, but we've never executed this branch other than in whitebox unittests.

**Comment by manish-qlogic** [comment]
> There should also be some integration tests for cancellation - we've made assumptions on how gRPC reports cancellation, but we've never executed this branch other than in whitebox unittests.

It is difficult to write consistent integration test for cancellation, This understanding is based on following observations.

## Test Cancel for operation still not reached to server

One of the strategy to test cancellation is described below;
1. gRPC call for operation A.
2. Block server by some means so that it won't accept new requests.
3. gRPC call for operation B followed by a cancellation.

here step 2 is hard to achieve either with embedded server([example](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/bigtable/testing/embedded_server_test_fixture.h)) or emulator([example](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/bigtable/tests/instance_admin_emulator.cc)).  I couldn't find a means to run single threaded server. The server picks up incoming request.

So, if client sends `AsyncBulkApply` followed by `AsyncReadRows` to server. Server picks up both the requests and starts processing both the requests.  Further `Cancel` request on  `AsyncReadRows` cancels the operation. 

A use of [`ResourceQuota`](https://grpc.io/grpc/cpp/classgrpc_1_1_resource_quota.html#details) to reduce the server thread count did not help either. The server responds back immediately with `grpc::Status::RESOURCE_EXHAUSTED(8)` for second call.

*note*: Need to investigate if [async server](https://github.com/grpc/grpc/blob/v1.19.0/examples/cpp/helloworld/greeter_async_server.cc) can be used for testing cancellation.

## Test Cancel by terminating ongoing streaming RPC
a. One idea is to perform   `AsyncBulkApply` and `AsyncReadRows`, then `Cancel` the operation `AsyncReadRows` during the processing.

This can be easily achieved either through embedded server or emulator. This results into a callback with `grpc::StatusCode::CANCELLED` for `AsyncReadRows`. `AsyncBulkApply` completes the operation normally.

b. Another idea is to perform   `AsyncBulkApply` and `AsyncReadRows`, then `Cancel` the operation `AsyncReadRows` and break the stream by terminating emulator. 

This results into a callback with `grpc::StatusCode::CANCELLED(1)` for `AsyncReadRows`. `AsyncBulkApply` ends up with `grpc::StatusCode::DEADLINE_EXCEEDED(4)`. 

so, though there is a way to test `Cancel` manually but it is difficult to write a consistent integration test case for it.
