### ISSUE TITLE
Decide on how assertions will work.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1402]
In #1398 it was proposed to add a `GCP_ASSERT` macro.

Some questions need to be answered:
 * should it throw, `::abort()` or use `google::cloud::Terminate`; throwing has the advantage of making tests easier but it can be accidentally caught, which might not be what the user of `GCP_ASSERT` expects
 * should `GCP_ASSERT(cond)` be equivalent to issuing a `GCP_LOG(FATAL)` when the condition is false?
 * if the answer to the above is yes, shall we add the failing logic to `google::cloud::Logger`?

IMO, the answers are:
 * use `google::cloud::Terminate` for coherency; one could install a handler throwing an exception for testing
 * yes
 * yes; actual failing should be implemented in `google::cloud::Logger::LogTo`

That way the `GCP_ASSERT` would be implemented along these lines:
```cpp
#define GCP_ASSERT(cond) \
((not (cond)) ? (GCP_LOG(FATAL) << "Assertion failed: " << #cond) : DummyStream())
```

That way, a `CGP_ASSERT(my_magic_condition) << "oh no";` would log:
"Assertion failed: my_magic_condition oh no" through the standard logger.

Thoughts?

**Comment by coryan** [comment]
I agree with your high-level objectives, the implementation will need to be different though. `GCP_LOG(FATAL)` expands to something like:

```C++
for (Logger blah; has_backend(...) and is_enabled(...); blah.dump()) blah
```

That definition will not (I think) work in your ternary expression.  It is defined as it is because it guarantees that the streaming expression is not evaluated if logging is disabled, or if there is no logging backend.  Even things like:

```C++
GCP_LOG(INFO) << ExpensiveFunction();
```

are cheap when logging is disabled, because `ExpensiveFunction()` is actually not called. Furthermore, there are some tricks to turn the whole thing into "nothing" if we know that a log level is disabled at compile-time.

What we need is something like:

`GCP_LOG_COND(level, cond)` that would expand to:

```C++
for (Logger blah; has_backend(...) and is_enabled(...) and (cond)); blah.dump()) blah
```

with:

```C++
#define GCP_ASSERT(cond) GCP_LOG_COND(FATAL, not (cond)) << "assertion failed: " << #cond
```

We can then define:

```C++
#define GCP_LOG(level) GCP_LOG_COND(level, true)
```

to avoid duplicating the complex `for()` based definition.

**Comment by coryan** [comment]
I am clearing who is assigned to this bug because none of us is actively working on it.

**Comment by coryan** [comment]
FWIW, `GCP_LOG(FATAL, ...)` always aborts now. I think that solves the problem of how to write assertions.
