### ISSUE TITLE
Document how to generate dependency graph.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1699]
This is just so we do not forget. In #1692 I changed the scripts to support generating dependency graphs. In general, one can generate these pretty easily:

```sh
$ git clone ...
$ cmake -H. -Bbuild-output
$ cmake --graphviz=graphviz/google-cloud-cpp.dot --build build-output
```

But the graphs are more accurate if the dependencies are pre-installed, instead of using `ExternalProject_Add`, for that use:

```sh
env NCPU=$(nproc) \
    CXX=g++ CC=gcc \
    TEST_INSTALL=yes \
    CREATE_GRAPHVIZ=yes \
    TRAVIS_OS_NAME=linux DISTRO=ubuntu DISTRO_VERSION=bionic \
    ./ci/travis/build-linux.sh
```

These should be moved to a nice markdown file in `doc/`, maybe under "how to build with strange settings."

**Comment by devjgm** [comment]
Note, this is also easy to do with bazel:

```sh
$ bazel query 'deps(//...) intersect //google/...' --output graph > graph.dot
$ dot -Tpng < graph.dot > graph.png
```

**Comment by remyabel** [comment]
I've been meaning to comment on this for a while just wanted to point out two things:

```
cmake --graphviz=graphviz/google-cloud-cpp.dot --build build-output
```

I don't think you can combine `graphviz` and `build`. You have to do something like `cmake --H. -Bout --graphviz`. I'm not sure if CMake changed something. Also, because this project has *a lot* of files I ran into the "too many open files" error.

This also can be done with Ninja:

```
ninja -t graph all | dot -Tpng -ograph.png
```

**Comment by devjgm** [comment]
People don't seem to care too much, and the documentation in this issue is pretty good too.
