### ISSUE TITLE
Version confusion in docs

### ISSUE THREAD

**Issue by lotten** [googleapis/google-cloud-cpp#1705]
As of right now:
- https://googlecloudplatform.github.io/google-cloud-cpp/latest/storage/index.html says 0.3.0 at the top of the page.
- https://googlecloudplatform.github.io/google-cloud-cpp/0.4.0/storage/index.html says 0.2.0 at the top of the page.

Meaning:
- "latest" in URL leads to 0.3.0
- "0.4.0" in URL leads to 0.2.0

Based on https://github.com/GoogleCloudPlatform/google-cloud-cpp/releases, 0.4.0 is actually the latest release right now.

**Comment by coryan** [comment]
Thanks for reporting this.  Yes, this is indeed confusing.  We have different libraries (Bigtable, Storage, and some common stuff) at different version numbers because, well, they started at different times, and some have more releases than others.  Which is not to say that it is less confusing.

@frankyn we should figure this out. We could split the libraries to one per repo (which has downsides in sharing infrastructure such as build scripts), or we should move all the libraries to the same version (which has downsides because it deviates from what users expect wrt to how versions get incremented), or fix the landing page to make it obvious what is going on.


/cc: @devjgm FYI.

**Comment by coryan** [comment]
@tmatsuo FYI, I think your changes may help us fix this for github.io too: if we upload to github.io with the new directory hierarchy you propose, then it would clear up this confusion too. Just a thought.

**Comment by tmatsuo** [comment]
@coryan Yeah, I think we can also use the new directory layout on github.io too, but I'm more inclined to migrate to the new hosting, which will also fix the issue :)

**Comment by tmatsuo** [comment]
We migrated to the new docs hosting, with a little bit different URL structures. I think we can close this now.

**Comment by tmatsuo** [comment]
and thanks for reporting @lotten !
