### ISSUE TITLE
Support alternative scope(s) in storage::oauth2::Credentials

### ISSUE THREAD

**Issue by timford** [googleapis/google-cloud-cpp#1866]
GoogleDefaultCredentials() uses the hardcoded "https://www.googleapis.com/auth/cloud-platform" scope when it produces credentials based on Service Account JSON credentials. A caller should be able to optionally pass a set of alternate scopes to use.

**Comment by houglum** [comment]
We can't do this for `GoogleDefaultCredentials()`, since that can create credentials w/ one of many underlying subtypes (authorized user creds and gce creds don't allow specifying scopes beyond what they were created with, for example).  However, it looks fairly easy to allow specifying a non-default set of scopes (which would replace the default(s)) for `ServiceAccountCredentials`, like the google-auth-library-python lib does here:
https://github.com/googleapis/google-auth-library-python/blob/b4eee9cb4086687be89802c330ecfa6e5c34e19b/google/oauth2/service_account.py#L108
