### ISSUE TITLE
Return Status from bigtable::TableAdmin::CheckConsistency

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#1948]
Rather than throwing on error, return `Status`. The signature should look like:

```c++
  Status CheckConsistency(bigtable::TableId const& table_id,
                        bigtable::ConsistencyToken const& consistency_token);
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 as an example

NOTE: This function is changing from returning `bool` to returning `Status`. This is slightly different from the other transformations that only change from void -> Status. However, `StatusOr<bool>` is a strange type that's of questionable use. I think a plain Status would be easier to use and have more meaning.

**Comment by dopiera** [comment]
By returning `Status` rather than `StatusOr<bool>` we're not able to indicate to the user that we've successfully checked that the replicas are inconsistent.

TBH, I'm not sure if we want to expose this API at all. It's supposed to allow the user to wait until replication catches up, so why not just make `WaitForConsistencyCheck` obtain the token and wait until replication catches up (just like `noex::Table::AsyncAwaitConsistency`)?

I can think of three legitimate (but at least weird) use cases that we'd be taking away from the users by removing `GenerateConsistencyToken` and `CheckConsistency` in favor of only `WaitForConsistencyCheck`:
 * getting the token in one process and waiting in another (why would anyone do it?)
 * waiting until replication catches up to a point in the past (in this case - why not start waiting in the past then?)
 * storing the token and reusing after a crash (why would anyone do it?)

It is worth noting, that the typical delay in a well provisioned cluster should be in the order of low number of minutes. In case of some long unavailability or severe underprovisioning, the delay is practically unbounded.

**Comment by devjgm** [comment]
Good point about how returning only a `Status` loses something. While not *wrong*, `StatusOr<bool>` is an odd duck, and often warrants closer look.

If we are going to keep `CheckConsistency`, I'll suggest two options

1. Return `StatusOr<bool>`. This will preserve all the semantics the code currently has. It's not wrong. But `StatusOr<bool>` can be a little error-prone to use.

2. Define an enum, like `enum class Consistency { kConsistent, kInconsistent };`, then have the function return `StatusOr<Consistency>`. This should make the calling code a bit more readable and less error-prone than `StatusOr<bool>`. It also future allows us to in the future return a 3rd (or more) value.

I slightly lean toward 2, but I could be easily convinced otherwise.

---

Also, I like your observation and question about whether this function should exist at all. If we can remove it completely without losing meaningful functionality from the API, that SGTM. I'd like to hear @coryan 's thoughts here.

**Comment by coryan** [comment]
In general, the client libraries should make it easier to do things that you can do with the raw gRPC (or REST) APIs, they should never remove functionality.  If it is possible to do something with the API, then it should be possible to do it with the client library (or at least we should think really hard before removing functionality).

> * getting the token in one process and waiting in another (why would anyone do it?)

Because I have a distributed app and I want all my shards to wait until the same consistency token.

Maybe I have multiple tables and I want to create a token for each one and then poll until all of them are done.

> * waiting until replication catches up to a point in the past (in this case - why not start waiting in the past then?)
> * storing the token and reusing after a crash (why would anyone do it?)

Because my application is being run by something like k8s where I may get terminated and restarted in another host and I do not want to wait for a *new* consistency point, that may take a long time and I already spent time waiting before.

Having a function like `WaitForConsistencyCheck` is super convenient, most users will probably only need that function. we should definitely have it. We should not remove the other functionality though.

Either `StatusOr<bool>` or `StatusOr<Consistency>` LGTM.

**Comment by dopiera** [comment]
Sounds like StatusOr<Consistency> it is.
