### ISSUE TITLE
Consider removing third_party/googleapis submodule

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#1989]
Sorry if this issue is already filed and I couldn't find it...

We should consider removing the third_party/googleapis git submodule. It's the only submodule that we currently use. It's only used by the cmake build, since (I think) bazel will fetch its deps on its own.

It may simplify the build strategy for this project if we cmake and bazel were a bit more similar, and if their of them required a git submodule.

If we decide not to do this, we can record our decision and rationale here.

**Comment by devjgm** [comment]
This is related to https://github.com/googleapis/google-cloud-cpp/issues/1248

**Comment by coryan** [comment]
So I started the work to do this.  It looks kind of funky, because we need to maintain a `CMakeList.txt` file (and we already maintain a `BUILD` file) to compile some code that we download from `googleapis`.

I think we should explore:

- Donating a `BUILD` file and a `CMakeLists.txt` file to the owners of `googleapis/googleapis`.  Last time I understood (via email) that they prefer not to keep language specific files in their code, but we should talk in person.
 - Create a repository (`googleapis/googleapis-cpp-protos` ??) where we maintain the build scripts for C++.  That way we can create some CI for it, and it becomes independant from google-cloud-cpp.

I am inclined to go with the second.  We should discuss with the GAPIC folks because we have common interests here.

@devjgm thoughts?

**Comment by devjgm** [comment]
The second option may be fine. I'm inclined to agree with your recommendation here. I also think it's an option for us to continue maintaining our own `BUILD` file and maintain our own cmake file as well, both within our current `google-cloud-cpp` repo. This would be pretty close to what we're doing now, I think. What are the downsides of doing this? It seems like this could be a first step toward the second option you mentioned.

**Comment by coryan** [comment]
> What are the downsides of doing this?

As we discussed during the meeting.  The GAPIC folks will probably need to compile the protos themselves.  If we also compile these we are going to have ODRs violations all over the place (I think).

Same thing with us compiling the (for example) Spanner protos and Bigtable protos on each library. The services share common protos, e.g. [IAM](https://github.com/googleapis/googleapis/tree/master/google/iam).

Having said that: I think we can make partial progress by using our own CMake files, the same files would go (almost verbatim) into new repository.
