### ISSUE TITLE
Do not throw exceptions from ClientOptions.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2082]
Since we are converting to only returning `StatusOr<>`.

**Comment by remyabel** [comment]
I would like to tackle this. My approach so far is pretty ugly, so I'm requesting your opinion on this approach. According to the TODO comment, `StatusOr` doesn't handle references well (like `std::optional`) so a workaround is to use `std::reference_wrapper`:

```c++
  google::cloud::StatusOr<std::reference_wrapper<ClientOptions>>
  set_connection_pool_size(std::size_t size) {
    if (size == 0) {
      return google::cloud::Status(
          google::cloud::StatusCode::kOutOfRange,
          "ClientOptions::set_connection_pool_size requires size > 0");
    }
    connection_pool_size_ = size;
    return google::cloud::StatusOr<std::reference_wrapper<ClientOptions>>(
        std::ref(*this));
  }
```

However, this now results in ugly and brittle code:

```c++
  auto client_options = bigtable::ClientOptions();
  auto status = client_options.set_connection_pool_size(1);
  ASSERT_STATUS_OK(status);
  auto admin_client =
      bigtable::CreateDefaultAdminClient("test-project", *status);
```

In particular, we can't do `auto client_options = bigtable::ClientOptions().set_connection_pool_size(1)` because otherwise there are lifetime issues, so it needs to be split up into two lines. That's fine for refactoring, but may be a landmine for future code.

**Comment by remyabel** [comment]
Here is a [minimal example](https://coliru.stacked-crooked.com/a/4c8b7ed341fd2e9c) showing the behavior with `std::reference_wrapper`. I don't know enough about the language to understand why this is happening.

**Comment by remyabel** [comment]
Thanks to the helpful folks at [StackOverflow](https://stackoverflow.com/a/55041074), it is pointed out that the `reference_wrapper` example has undefined behavior. Instead, it needs to be changed to `bigtable::ClientOptions().client_options.set_connection_pool_size(1).get()`. Still, forgetting to add `get()` is still a landmine.

**Comment by coryan** [comment]
So a couple of ideas:

- Return `Status`, and give up on the nice builder API.
- Think of a nice semantic meaning for `0` as a valid argument, e.g., "reset to the default value" and never return an error.

I think I like the second for `set_connection_pool_size()`.
