### ISSUE TITLE
Use StatusOr<> in CompletionQueueImpl.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2083]
Since we are converting to only returning `StatusOr<>`.

**Comment by dopiera** [comment]
I've identified that we throw in `CompletionQueue` only in these cases:
* the gRPC library behaves differently than documented
* we corrupted the registry of ongoing operations

IMHO we should use assertions where we currently throw. I doubt that the library would be of any use if any of the assertions were not held. We don't even test for those erroneous scenarios because we believe they don't happen.

The code without `StatusOr` would yield less boilerplate.

Due to that, we should probably implement #1402 first.

**Comment by coryan** [comment]
Given @dopiera's observations I am going to remove this from the GA milestone.

**Comment by devjgm** [comment]
Not needed.
