### ISSUE TITLE
Remove Mutation body from FailedMutation.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2093]
Now that the Bigtable functions take `SingleRowMutation` and `BulkMutation` by value the motivation to return the original mutation in `FailedMutations` is gone.  It used to be that the application *had* to transfer the data to the library, and it seemed impolite to drop the data on the floor on failures.

But now they have chosen to transfer the data (or we just got a copy), I do not see the need to return it.

**Comment by coryan** [comment]
@rsimion is this something you can tackle?

**Comment by rsimion** [comment]
I can give it a try.

**Comment by devbww** [comment]
Greg and I were chatting about the awkwardness of using original_index() to get back the SingleRowMutation/row_key when handling errors.  For example, in #2169 we even just commented out some test expectations on the FailedMutation rather than update them.  Also see recent changes to some local client code, where we are forced to pass a BulkMutation by value and then extract its protobufs in order to report the failing row key.  Perhaps keeping FailedMutation::mutation_ isn't so bad?

**Comment by coryan** [comment]
I am not opposed to the idea, but if you do, make sure you use move semantics because mutations can be large (multiple MiB each).

**Comment by coryan** [comment]
reviewed, closing.
