### ISSUE TITLE
Add sample snippets on cluster for better documentation

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2266]
This issue/task is a result from #2253

cluster.js file has following snippets that are not part of BigTable C++ Client,
[bigtable_exists_cluster](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/cluster.js#L56)
[bigtable_cluster_get_meta](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/cluster.js#L93)
[bigtable_cluster_set_meta](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/cluster.js#L112)

If proven worthy, we need to write similar snippets in BigTable C++ client.

**Comment by dbolduc** [comment]
closing this issue because

1. These snippets in other libraries were moved to `bigtable_api_*` and used for internal api docs only. (not for the public cloud bigtable snippets)
2. We do have [this example](https://cloud.google.com/bigtable/docs/samples/bigtable-get-cluster) for getting cluster metadata (and thus checking if it exists).
3. There is also [this example](https://googleapis.dev/cpp/google-cloud-bigtable/latest/classgoogle_1_1cloud_1_1bigtable_1_1v1_1_1InstanceAdmin.html#afe746ee1bcfd82bcbcf9e96d987e1597) for setting cluster metadata, but I think it will be removed shortly due to #5923
