### ISSUE TITLE
Create code snippet for bigtable_get_table_meta

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2300]
Need to create code snippet for documentation purposes.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/table.js#L74)

**Note:** This issue/task is outcome of #2253

**Comment by coryan** [comment]
Confusingly, there are two samples in node.js, one called `bigtable_get_table_meta`:

https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/table.js#L74

and one called `bigtable_get_table_metadata`:

https://github.com/googleapis/nodejs-bigtable/blob/0d8412140ceb32bf70837c6d18d5d2ce47ffba78/samples/tableadmin.js#L51-L58

I think we should use the `_metadata` one, because it is in the tracker, while the other one is not. Closing this bug for now.
