### ISSUE TITLE
Implement ObjectMetadata::set_storage_class

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2322]
Correct me if I'm wrong, I don't think there's currently any implementation for this. We can either model it after this:

https://github.com/googleapis/google-cloud-cpp/blob/7b26e02f7ce8b47580cd6c242edff8e503272e87/google/cloud/storage/bucket_metadata.h#L780

Or create a `WellKnownParameter`. The reason being is that the [docs](https://cloud.google.com/storage/docs/changing-storage-classes) state changing the object's storage class is a rewrite operation.

**Comment by coryan** [comment]
You are correct, we need a `set_storage_class()` member function because:

- To create objects with a different storage class from their Bucket's default we need; to call [`Objects: insert`](https://cloud.google.com/storage/docs/json_api/v1/objects/insert) with payload that includes a different storage class.
- To rewrite an object with a different storage class we need to start a rewrite with a payload that modifies the storage class.

> The reason being is that the docs state changing the object's storage class is a rewrite operation.

Correct, one cannot change the storage class by just setting the object metadata. One needs to rewrite the object.

**Comment by coryan** [comment]
Note that to write good integration tests we need the testbench to reject changes that modify the storage class via metadata operations.
