### ISSUE TITLE
  client.CreateV4SignedUrl() does not work when object_name == ""

### ISSUE THREAD

**Issue by rsimion** [googleapis/google-cloud-cpp#2350]
In storage/tests/client_sign_url_integration_test.cc
    client.CreateV4SignedUrl() does not work when object_name == ""

The actual url is different than the expected url.
```
EXPECT_EQ(expected, *actual); 
```
fails.
Related to #2250

**Comment by remyabel** [comment]
Can you be more specific about what it does wrong when `object_name` is empty?

**Comment by rsimion** [comment]
@remyabel 
sorry, just updated the ticket.

**Comment by remyabel** [comment]
Can you please give me an example? This is what I get from testing:

```
https://storage.googleapis.com/thisisatest1234567
?x-goog-signature=...
&x-goog-algorithm=GOOG4-RSA-SHA256
&x-goog-credential=service-account%40project.iam.gserviceaccount.com%2F20190327%2Fus-east1%2Fstorage%2Fgoog4_request
&x-goog-date=20190327T162007Z
&x-goog-expires=600
&x-goog-signedheaders=host
```

formatted for readability. It looks pretty much identical to output from gsutil.

**Comment by rsimion** [comment]
@remyabel 
This is related to a new PR #2250 that has not been merged yet.
 If you look at the new file client_sign_url_integration_test.cc that is under review at line 148    EXPECT_EQ(expected, *actual); fails for object_name == "" ( line 112)

**Comment by remyabel** [comment]
There are two potential causes I think:

- Either your assert is firing at line 147 `EXPECT_THAT(*actual, HasSubstr(object_name));`, or:
- The test case with no object specified, i.e `https://storage.googleapis.com/test-bucket/` is tripping it up (notice the trailing slash. The example I showed has no trailing slash)

**Comment by coryan** [comment]
For what is worth, we should check if the signed URL created by the C++ client library works when `object_name == ""`.  If it does, then it is probably a bug in the expectations from the `.json` file.  If it does not work, then we need to fix our library.

**Comment by rsimion** [comment]
@remyabel 
Just commented out 
```
 EXPECT_THAT(*actual, HasSubstr(object_name));
```
and it still failed.

I cannot see anything at
https://storage.googleapis.com/test-bucket/?X-Goog-Algorithm  
I get 
```<code>AccessDenied</code>
```

**Comment by remyabel** [comment]
Try removing the trailing slash. Neither the library nor `gsutil` output a trailing slash after `test-bucket`.

**Comment by remyabel** [comment]
After rereading the .NET code for a couple of hours I think there might be a bug (or oversight). Please check my math:

This is the code where we are getting the JSON data:

https://github.com/googleapis/google-cloud-dotnet/blob/b1c4be61412aeb6e261e2be38c568678b9ed73f3/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/UrlSignerTest.V4SignerTest.cs#L114

And these lines are where we decide whether or not to append `objectName`:

https://github.com/googleapis/google-cloud-dotnet/blob/b1c4be61412aeb6e261e2be38c568678b9ed73f3/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1/UrlSigner.V4Signer.cs#L144-L148

The problem I think is that since it is checking for `null` instead `string.Empty`, **and** because `object` is `""` instead of `NULL`, it's appending a trailing slash.

**Comment by rsimion** [comment]
@remyabel  you are right
```
if (objectName != null)
```
seems to be the problem. the string is empty but is not null.

**Comment by remyabel** [comment]
FYI, I've opened a PR over there.

**Comment by coryan** [comment]
@remyabel it is possible that the error is in the JSON file that drives these tests, maybe it should be setting the `object_name` field to null here:

https://github.com/googleapis/google-cloud-dotnet/blob/b1c4be61412aeb6e261e2be38c568678b9ed73f3/apis/Google.Cloud.Storage.V1/Google.Cloud.Storage.V1.Tests/UrlSignerV4TestData.json#L116

@frankyn FYI.

**Comment by frankyn** [comment]
Question, the trailing slash should work, could I get a full example that doesn't work? 

`https://storage.googleapis.com/test-bucket/?X-Goog-Algorithm` is not a complete signed URL.

**Comment by remyabel** [comment]
> Question, the trailing slash should work, could I get a full example that doesn't work?

I apologize for the confusion. The question is whether or not there should be a trailing slash if `object_name` is empty or `null`. Currently, the .NET library only checks if it is null, so it outputs a trailing slash if the string is empty. 

```c#
if (objectName != null)
{
    _resourcePath += $"/{Uri.EscapeDataString(objectName)}";
}
```

The C++ library checks for `empty()` and only outputs a trailing slash if the string is not empty.

```c++
if (!object_name().empty()) {
    os << '/' << curl.MakeEscapedString(object_name()).get();
}
```

gsutil does not output a trailing slash if you omit the object name. IMO, only checking if it's `null` is a logical error because the JSON value can either be `null` or `""`, hence my PR.

And the test data we are using is from the .NET library (linked to by @coryan above):

```
https://storage.googleapis.com/test-bucket/?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=test-iam-credentials%40dummy-project-id.iam.gserviceaccount.com%2F20190201%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20190201T090000Z&X-Goog-Expires=10&X-Goog-SignedHeaders=host&X-Goog-Signature=2a1d342f11ddf0c90c669b9ba89ab5099f94049a86351cacbc85845fd5a8b31e1f9c8d484926c19fbd6930da6c8d3049ca8ebcfeefb7b02e53137755d36f97baab479414528b2802f10d94541facb888edf886d91ba124e60cb3801464f61aadc575fc921c99cf8c52e281f7bc0d3e740f529201c469c8e52775b6433687e0c0dca1c6b874614c3c3d09599be1e192c40ad6827416e387bf6e88a5f501f1d8225bce498d134599d0dfe30c9c833c244d3f90cf9595b9f8175658b788ee5c4a90b575fde5e83c645772250c7098373ca754b39d0fc1ebca2f50261a015931541c9827920eba67a1c41613853a1bd23299a1f9f5d583c0feb05ea2f792ba390d27
```

So it seems to be a little inconsistent and if you could tell us the correct behavior, that would be much appreciated.

**Comment by frankyn** [comment]
I chatted with a PoC for V4 Signature support in the GCS team about it. 
There is no recommendation as they both should work. 

Given `gsutil` does not have a trailing slash, let's at least be consistent with the CLI tool.

Thanks for raising this @rsimion and for clarifying @remyabel.

**Comment by coryan** [comment]
Assigning to myself for now at least until triaged.

**Comment by coryan** [comment]
@rsimion is fixing this as part of #2250.
