### ISSUE TITLE
Add policy document condition error checking.

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-cpp#2440]
As an enhancement, it would be nice to have some error checking to make sure the supplied fields are valid. The nodejs approach is [here](https://github.com/googleapis/nodejs-storage/blob/master/src/file.ts#L2094).

- Check that the expiration timestamp is valid.
- Check the expiration date is not in the past.
- Check that conditions contain correct amount of elements.

**Comment by remyabel** [comment]
I'm not sure what the best way to tackle this is. Spit-balling some ideas:

1. Disallow modifying `conditions` directly and force the user to use the helper functions to create the conditions.

2. Use `json.parse` on the `conditions` and use the nljson API to determine if the supplied arguments are valid integers.

3. Have the user pass `Options` similar to `SignedURL` and the nodejs approach.

4. Use a heterogeneous `std::vector` instead of a `std::vector<std::string>`.

Approach 1 is the simplest approach, but we will also need to allow the user to set `cache-control`, `cache-disposition`, et al (see the [docs](https://cloud.google.com/storage/docs/xml-api/post-object) for a full list).

**Comment by remyabel** [comment]
cc @coryan as his PR's are changing relevant parts of code. We may as well go all out with approach 3.

Also the new guys @scotthart @mr-salty in case they have any ideas to contribute.

**Comment by remyabel** [comment]
Close this? I think this would duplicate server-side error checking and I created this before I saw the ADR.

**Comment by coryan** [comment]
SGTM. Closing.
