### ISSUE TITLE
How to create folder in gcs using client api?

### ISSUE THREAD

**Issue by GaoleMeng** [googleapis/google-cloud-cpp#2468]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?
No

### What component of `google-cloud-cpp` is this related to?

- Cloud Storage (under development).

### What were you trying to do?
I'm trying to use the cpp client api to create folder onto one bucket, I didn't find an api to do that. The closest I can find is UploadFile, but that does not work for creating folder

Thanks!

**Comment by coryan** [comment]
That is because Google Cloud Storage does not really have folders.  You can create an object called `foo/bar/baz.txt` without having to create `foo/` or `foo/bar/` as folders first:

https://stackoverflow.com/questions/38416598/how-to-create-an-empty-folder-on-google-storage-with-google-api
https://cloud.google.com/storage/docs/gsutil/addlhelp/HowSubdirectoriesWork
