### ISSUE TITLE
Remove CompletionQueue parameter from Async*() functions.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2567]
Instead the `*Client` should take the `CompletionQueue` as a parameter in its constructor, probably wrapped in a "Concurrency Policy" or something similar.

If no `CompletionQueue` is provided the functions should create a completion queue on demand, and block until the result is ready, effectively the default is "NoConcurrency" or "Synchronous".

**Comment by dopiera** [comment]
FWIW, here is a POC showing how this can be done:
https://github.com/dopiera/google-cloud-cpp/commit/51dbf0f5835795203333dcc2a912a71d89f902ad

**Comment by dopiera** [comment]
I've spent some significant amount of time trying different approaches to implement it.

My goals were:
* we need something that is going to make it nearly impossible for us to:
  * forget to wait for the operation in the "Synchronous" case
  * forget to call `Run` on the `CompletionQueue` in the "Synchronous" case
  * use a wrong `CompletionQueue` (a temporary instead of a provided one)
* will not require us to effectively duplicate every asynchronous test

I think I achieved all of the goals in https://github.com/dopiera/google-cloud-cpp/commit/396ec5d220117f42d7d36da09ea0adb08b2c4c17.

Unfortunately there is IoC, but it's synchronous code, so the current codebase can almost be converted by a script.

The proposal is to introduce a `CompletionQueueProvider` to every client. It would optionally hold a `CompletionQueue` executed by an external thread(pool).
`CompletionQueueProvider` has one member function: `WithCompletionQueue(Functor)`, which synchronously executes the functor with either the user-provided `CompletionQueue` or with a temporary one. The functor should start the asynchronous operation and return a future (just like all `Async*` operations are implemented). In the "Synchronous" case it also adds a `then` to the returned future, which will shut down the temporary `CompletionQueue` after the operation is complete.

**Comment by dopiera** [comment]
@coryan Carlos, do you think that this approach is the way to go? If yes, I will.

**Comment by coryan** [comment]
I really like the `WithCompletionQueue()` function. The names do not speak to me, so I am going to propose slightly different ones:

- Rename `CompletionQueueProvider` to `CompletionQueueExecutor`.
- Rename `WithCompletionQueue` to `Post`.

I am basically borrowing the names from the `executors` proposal (http://chriskohlhoff.github.io/executors/).

I would like (if possible) to hide this behind some helper functions, the `ExecutionPolicy` should not be a public API:

```C++
void UseAsyncThings(cbt::table table) {
  auto future = table.AsyncReadRow(...);
  ...
}

void MakeEverythingBlock() {
  cbt::Table table(..., BlockingExecutionPolicy());
  UseAsyncThings(table);
}

void MakeEverythingAsynchronous() {
  cbt::CompletionQueue cq;
  std::thread t([](CompletionQueue cq) { cq.Run(); }, cq);
  t.detach();

  cbt::Table table(..., AsynchronousExecutionPolicy(cq));
  UseAsyncThings(table);
}
```

I am not sure what the `AsynchronousExecutionPolicy()` and `BlockingExecutionPolicy()` functions return. It could be a "ExecutionPolicyConfig" or they *could* return different types, all we need is to override the right `ChangePolicy()` functions.

**Comment by coryan** [comment]
Also, we should think a little bit about how `ReadRows()` (plural) would look like.

**Comment by dopiera** [comment]
I totally agree that your names are better.

I don't follow, the second part, unfortunately.

My understanding was that the only change to the public API is that the `CompletionQueue&` parameter goes away from `Async*` functions and all the clients: `Table`, `InstanceAdmin` and `TableAdmin` get an additional parameter, along the lines of what the `AsynchronousExecutionPolicy()` or `BlockingExecutionPolicy()` functions return.

Is your intention to make the type returned from `AsynchronousExecutionPolicy()` as opaque as a lambda, so that the user cannot store it or explicitly create such an object?

If yes, I imagine it is doable, e.g. via a lambda accepting a private member of a class, or something along those lines.

**Comment by coryan** [comment]
> 
> My understanding was that the only change to the public API is that the `CompletionQueue&` parameter goes away from `Async*` functions

Yes.

> and all the clients: `Table`, `InstanceAdmin` and `TableAdmin` get an additional parameter, along the lines of what the `AsynchronousExecutionPolicy()` or `BlockingExecutionPolicy()` functions return.

I think I complicated things too much... let me see if I can explain.

> 
> Is your intention to make the type returned from `AsynchronousExecutionPolicy()` as opaque as a lambda, so that the user cannot store it or explicitly create such an object?

I think the original intent was to add a `CompletionQueue` parameter to (for example) the `Table` constructor.  I suggest that we wrap the completion queue parameter in a type that tells the user *why* they are passing this parameter, so maybe we have:

```C++
struct BlockingExecutionPolicy { BlockingExecutionPolicy() {} };
struct AsynchronousExecutionPolicy {
 explicit AsynchronousExecutionPolicy(CompletionQueue c) : cq(std::move(c)) {}
 CompletionQueue cq;
};
```

Then the application gets a better sense of what this is doing:

```C++
cbt::Table table(..., AsynchronousExecutionPolicy(my_completion_queue));
```

That was it, just changing some names to make the intent more obvious.
