### ISSUE TITLE
Compilation problem using XCode 6.2

### ISSUE THREAD

**Issue by jodogne** [googleapis/google-cloud-cpp#2818]
### What component of `google-cloud-cpp` is this related to?

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

0.10.0

### What compiler and version are you using?

$ xcodebuild -version
Xcode 6.2
Build version 6C131e

### What operating system and version are you using?

Using XCode on Apple OS X.

### What were you trying to do?

I am trying to compile the library from source.

### What did you expect to see?

Successful compilation.

### What did you see instead?

During the compilation, `xcodebuild` reports the following error:

```
In file included from /Users/jodogne/Subversion/orthanc-gcp/Build/google-cloud-cpp-0.10.0/google/cloud/storage/bucket_metadata.cc:20:
In file included from /Users/jodogne/Subversion/orthanc-gcp/Build/google-cloud-cpp-0.10.0/google/cloud/storage/internal/bucket_requests.h:18:
In file included from /Users/jodogne/Subversion/orthanc-gcp/Build/google-cloud-cpp-0.10.0/google/cloud/iam_policy.h:18:
/Users/jodogne/Subversion/orthanc-gcp/Build/google-cloud-cpp-0.10.0/google/cloud/iam_bindings.h:91:14: error: chosen constructor is explicit in
      copy-initialization
      return {};
```

**Comment by coryan** [comment]
According to Wikipedia's [XCode page](https://en.wikipedia.org/wiki/Xcode) 6.2 is "discontinued", and it is based on LLVM 3.5, older than the versions we usually test with. In fact, our [README](https://github.com/googleapis/google-cloud-cpp/blob/master/README.md#compiler) recommends XCode 8.3 or higher (because we require Apple's CLang >= 8.1).

I am sorry, but your toolchain is too old for us to support. We will gladly accept a workaround (assuming it is not too ugly) if somebody submits a PR.
