### ISSUE TITLE
Change bigtable/benchmarks to compile with exceptions disabled.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2877]
For mostly historical reasons the benchmarks only compile with exceptions enabled.

**Comment by remyabel** [comment]
For removing the exception from `BenchmarkSetup`, what is your preferred course of action? The most straight forward approach is to use a boolean and have a `is_setup()` flag. Something like:

```C++
  auto usage = [this, argv](char const* msg) {
    # ... snip ...
    std::cerr << msg;
    this->is_setup_ = false;
  };

  if (argc < 4) {
    usage("too few arguments for program.");
    return; # return instead of throwing an exception
  }

  # ... snip ...

  is_setup_ = true;
```

Then we would need to explicitly check if `benchmark_setup.is_setup()` before using it (otherwise we'll call it "undefined behavior", but I am open to more rigorous ways of handling it), something like:

```C++
BenchmarkSetup blah(...);
ASSERT_TRUE(blah.is_setup());
```

Unfortunately, this is causing the tests to fail, so I am open to other ideas.

**Comment by coryan** [comment]
The common practice is to have a factory function that returns `StatusOr<BenchmarkSetup>` (or std::unique_ptr<BenchmarkSetup>`) and make the constructor private. Alternatively return `StatusOr<BenchmarkSetupData>` from the factory function, where `BenchmarkSetupData` is a plain struct consumed by the (public) `BenchmarkSetup` constructor.

Neither are awesome, for obvious reasons.
