### ISSUE TITLE
Investigate errors upon file cleanup in windows bazel build

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp#2949]
The windows bazel build passes, but I see some errors in the cleanup code:

```
Get-ChildItem : The directory name is invalid.
At line:1 char:4
+ & {Get-ChildItem -Recurse -File -Exclude test.xml,sponge_log.xml,buil ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (T:\src\github\g...thon_wrapper.sh:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand
Get-ChildItem : The directory name is invalid.
At line:1 char:4
+ & {Get-ChildItem -Recurse -File -Exclude test.xml,sponge_log.xml,buil ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (T:\src\github\g...arty\zlib.BUILD:String) [Get-ChildItem], IOException
    + FullyQualifiedErrorId : DirIOError,Microsoft.PowerShell.Commands.GetChildItemCommand
```

**Comment by coryan** [comment]
We could simply remove that code if it does not help.

**Comment by devjgm** [comment]
Have we seen anymore of these errors? If not, maybe we should just close this issue.

**Comment by coryan** [comment]
These are just harmless. The build scripts try to remove any artifacts created by the build for reasons [1], it just happens that no such artifacts are present in these builds (they are in the `C:\b` directory).

[1]: We remove the artifacts because Kokoro performs an rsync after the build which is extremely slow on Windows, we are implementing the recommended workaround b/79892746
