### ISSUE TITLE
Potential socket leaks in storage::Client.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2953]
Seems like we are leaking sockets (or at least not closing them quickly enough) when we write code like this:

```C++
void F() {
  for (int i = 0; i != 100; ++i) {
    storage::Client client;
    auto stream = client.ReadObject(...);
    // read some data from stream
  }
}
```

vs. code like this:

```C++
void F() {
  storage::Client client;
  for (int i = 0; i != 100; ++i) {
    auto stream = client.ReadObject(...);
    // read some data from stream
  }
}
```

**Comment by dopiera** [comment]
I'm afraid I cannot reproduce it.

I've attempted to basically replicate the code from the above snippet, but number of descriptors seems to exactly follow the number of clients (I haven't seen a delay).
https://github.com/dopiera/google-cloud-cpp/commit/6d5cae61f03c3a679b4a622796ec924159d00ef7

In order to check the method, I verified that having 1000 open clients, means 1000 descriptors more.

@coryan are you aware of any extra circumstances which could have led to the leak/blow-up?

**Comment by coryan** [comment]
> I'm afraid I cannot reproduce it.

That is good news, and not completely unexpected.

> I've attempted to basically replicate the code from the above snippet, but number of descriptors seems to exactly follow the number of clients (I haven't seen a delay).

That is good enough for me.  Is it possible to write a test, even if it requires monitoring some `/proc/*` file on Linux?

If not, we can simply close this bug.
