### ISSUE TITLE
internal::SetEnv inconsistent behavior on Windows and other systems

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp#3027]
I found this on https://github.com/googleapis/google-cloud-cpp-spanner/pull/475

This code behaves differently on windows and other systems:
```
google::cloud::internal::SetEnv("WHATEVER", "");
google::cloud::internal::GetEnv("WHATEVER").has_value();
// false on Windows and true on other systems.
```
I think it's because of the spec of `putenv_s`.

[putenv_s](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/putenv-s-wputenv-s?view=vs-2019):
> You can remove a variable from the environment by specifying an empty string (that is, "") for value_string.

**Comment by remyabel** [comment]
I think on Windows there's no way to create an empty environment variable without doing something like setting it to a space. Should we have:

```
google::cloud::internal::SetEnv("WHATEVER", "");
```

do `putenv_s(var, " ")` on Windows? Or do we change the behavior of `SetEnv` so that an empty string deletes the environment variable? I lean towards the ladder since doing `SetEnv("WHATEVER", nullptr)` or `UnsetEnv` is more explicit when deleting a variable.

**Comment by tmatsuo** [comment]
@remyabel 
Thanks!
How about the third option of doing nothing other than adding a documentation?

**Comment by remyabel** [comment]
Fine by me. But I'll leave the tests in since they didn't exist before and it complements the documentation.
