### ISSUE TITLE
Intermittent "Missing row key at last chunk in cell" error

### ISSUE THREAD

**Issue by jkuszmaul** [googleapis/google-cloud-cpp#3210]
### Does this issue affect the `google-cloud-cpp` project?

Per @igorbernstein2 in the slack, this sounded like a language-specific issue, so probably.

### What component of `google-cloud-cpp` is this related to?

- Cloud Bigtable.

### What version of `google-cloud-cpp` are you using?

v0.10.0 (ec468fbc06cca36802323c50d32180a149ec467a)

### What operating system and version are you using?

Debian Stretch

### What were you trying to do?

I was querying a range of rows, using a `google::cloud::bigtable::Filter::Latest(1)` filter. This occurred with a couple of different ranges, although the times I noticed it it was all on ranges that were within relatively close proximity of each other in the key space. It was too intermittent, and went away too quickly, to debug much.

### What did you expect to see?

To query rows, then CHECK the `StatusOr` returned by the `RowReader` iterator, and have the CHECK succeed.

### What did you see instead?

The CHECK failed and the status message said `Missing row key at last chunk in cell [INTERNAL]`

**Comment by jkuszmaul** [comment]
Note that this behavior seems to have gone away, and only caused intermittent issues for an hour or two, and was on a development BigTable instance. I have not observed this particular issue before, with this exact setp.

**Comment by coryan** [comment]
Thank you for filing the detailed bug report.  I am going to assume this is a library bug and go from there.

**Comment by jkuszmaul** [comment]
Hmm, just hit this again, in a different part of the keyspace of my table than I had issues with last time. I'll see if I can figure out any patterns.

**Comment by jkuszmaul** [comment]
System certainly wasn't under any particularly high load--CPU was at ~30-40% (in the middle of write operations going on in parallel--I have not noticed any writes failing). I am reading from a different part of the key space than I am writing.

**Comment by jkuszmaul** [comment]
Yeah, still way too little information to figure out if there're any meaningful patterns (the thing about the ranges that had errors being in similar parts of the keyspace in the original ticket may've just been luck). Our usage of the table means we don't have a particularly consistent read load (it is a developer instance, and we are still using it largely as an experiment currently), so we don't actually have a huge sample size to provide reports on.

**Comment by coryan** [comment]
The code generating this error is pretty easy to find:

https://github.com/googleapis/google-cloud-cpp/blob/9018cf2199a6f3cad68552e4b5849918e93f6502/google/cloud/bigtable/internal/readrowsparser.cc#L87-L95

I have not looked at this code in a while, but nothing jumps at me as an obvious problem.

Is there a chance you can add some debugging information?  Maybe print the `.DebugString()` for `chunk`?

**Comment by jkuszmaul** [comment]
Sure, I can add debugging info and then report it when I encounter this next. Anything other than `chunk.DebugString()` that you'd suggest?

**Comment by coryan** [comment]
The current state of this class would be useful.  Specifically: `row_key_`, `cells_.size()`, `cell_first_chunk_`, `last_seen_row_key_`, `row_ready_`, `end_of_stream_`.  I think `cell_.row` might also be handy.

**Comment by coryan** [comment]
I ran the unit tests and the code in question is triggered only on "invalid" conditions.  Which is not to say that the code is correct, the code could *also* be triggering on valid conditions *or* the tests could be broken.  It just says that we did not expect this code to be executed when the messages are flowing normally.

@igorbernstein2 I think the last time we took a snapshot of the test suite for the C++ client was about 2 years ago (I just created #3215 to update this).  I assume there is a new version since then?  Does anything here ring a bell?

https://github.com/googleapis/google-cloud-cpp/blob/9018cf2199a6f3cad68552e4b5849918e93f6502/google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc#L40

https://github.com/googleapis/google-cloud-cpp/blob/9018cf2199a6f3cad68552e4b5849918e93f6502/google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc#L57

https://github.com/googleapis/google-cloud-cpp/blob/9018cf2199a6f3cad68552e4b5849918e93f6502/google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc#L871

https://github.com/googleapis/google-cloud-cpp/blob/9018cf2199a6f3cad68552e4b5849918e93f6502/google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc#L1356

https://github.com/googleapis/google-cloud-cpp/blob/9018cf2199a6f3cad68552e4b5849918e93f6502/google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc#L1373

https://github.com/googleapis/google-cloud-cpp/blob/9018cf2199a6f3cad68552e4b5849918e93f6502/google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc#L1398

**Comment by jkuszmaul** [comment]
I was able to trigger this error (not sure if it shares a root-cause or not) by Ctrl-C'ing the process in the wrong spot. This may point to me poorly handling some threading or signal handling (although the previous instances were not due to sending SIGINT to the process), although I didn't think I was doing anything problematic.

Since I did capture the debug information, and since it may be the same root cause, here's what I got:

```
chunk.ShortDebugString(): row_key: [redacted, but normal looking] family_name { value: [redacted, but normal] } qualifier { value: [redacted, but normal] } timestamp_micros: 1571280751549000 value: [redacted, but normal] commit_row: true
Class state:
row_key_: ""
cells_.size(): 0
cell_first_chunk: 0
last_seen_row_key: [redacted, but normal looking]
row_ready_: 0
end_of_stream_: 0
```

**Comment by jkuszmaul** [comment]
Just got this naturally (no Ctrl-C), debugging information same, except on a different row and with `cell_first_chunk_ = 1`.

**Comment by jkuszmaul** [comment]
And now I got it with an entirely empty chunk, and `cell_first_chunk_ = 0`.

**Comment by coryan** [comment]
> Just got this naturally (no Ctrl-C), debugging information same, except on a different row and with cell_first_chunk_ = 1, and the value in the chunk was not populated.

That is odd, to get to the problem line, you need to pass this:

https://github.com/googleapis/google-cloud-cpp/blob/9018cf2199a6f3cad68552e4b5849918e93f6502/google/cloud/bigtable/internal/readrowsparser.cc#L78

**Comment by coryan** [comment]
I have tried several things and cannot reproduce the problem.  I wonder if you could tell me more about your application (threading model for example, size of keys and values).  Feel free to contact me directly, same username at google.com if you don't want to discuss this in a public forum.

Alternatively, maybe you can add additional login (this is expensive, so not quite what you want in production).  For example https://github.com/coryan/google-cloud-cpp/commit/412734da5f117b55328fb2fba0fef636df13e0aa captures the state of the class before and at the error point?

**Comment by jkuszmaul** [comment]
One of my coworkers managed to get me a reproducible test case, and I tracked down some bad memory accesses on my end.
If it turns out that those weren't the cause, then I'll reopen this. Thanks @coryan for your help.
