### ISSUE TITLE
Update Bigtable RowReadParser acceptance tests

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3215]
These tests are executed from a test suite (see `bigtable/tools/*.py`), we should get a new version, generate the tests and see if anything breaks.

**Comment by coryan** [comment]
I looked, and nothing has changed since the last time we took a snapshot.

**Comment by igorbernstein2** [comment]
Just wanted to make sure you were looking at https://github.com/googleapis/conformance-tests/tree/master/bigtable/v2?

**Comment by coryan** [comment]
If that is the new source of truth we should at least change the scripts to use it instead.

**Comment by amitchauhan1007** [comment]
In the new json file (https://github.com/googleapis/conformance-tests/blob/master/bigtable/v2/readrows.json), there is a mismatch between "chunks/ExtractCells" values and the "results/expected_cells" values. Due to which many test cases are failing. 

For example see below values of "chunk" and "results/expected_cell" (from readrowsparser_acceptance_tests.inc) and the output error message:
*********************************
For ex: // Test name: "simple row with timestamp"
TEST_F(AcceptanceTest, SimpleRowWithTimestamp) {
  std::vector<std::string> chunk_strings = {
      R"chunk(
      row_key: "Uks="
      family_name: < value:"A">
      qualifier: < value:"Qw==">
      timestamp_micros: 100
      value: "dmFsdWUtVkFM"
      commit_row: true
        )chunk",
  };

  std::vector<std::string> expected_cells = {
      "rk: RK\n"
      "fm: A\n"
      "qual: C\n"
      "ts: 100\n"
      "value: value-VAL\n"};
  EXPECT_EQ(expected_cells, ExtractCells());
}

Test execution error:
Expected equality of these values:
  expected_cells
    Which is: { "rk: RK\nfm: A\nqual: C\nts: 100\nvalue: value-VAL\n" }
  ExtractCells()
    Which is: { "rk: Uks=\nfm: A\nqual: Qw==\nts: 100\nvalue: dmFsdWUtVkFM\nlabel: \n" }
**********************************

Note: In previous json (https://raw.githubusercontent.com/GoogleCloudPlatform/cloud-bigtable-client/master/bigtable-client-core-parent/bigtable-client-core/src/test/resources/com/google/cloud/bigtable/grpc/scanner/read-rows-acceptance-test.json), both the data structures (chunk and results) are having similar values and tests are passed on execution.

 Need to know if the values are as expected OR need to be changed to match "chunks" and "results" values .

**Comment by coryan** [comment]
Looks to me (but maybe we should add a README to that `conformance-tests` repository) that the new JSON file is in protobuf JSON format.  I expect that some values are stored as base64 encoded strings, but our parsing script is not converting the base64 strings to the actual strings.

It might be simpler to use the protobuf utilities to read the JSON file into a protocol buffer:

https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html

or even:

https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util

**Comment by amitchauhan1007** [comment]
Hi,
Thanks for your quick response.  Will it be okay if we write some code in our parsing script only to convert base64 encoded strings to the actual strings
