### ISSUE TITLE
Allow running a custom command for docker in the build scripts

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-cpp#3266]
In Fedora 31, docker has been replaced by moby-engine which doesn't support cgroups v2 (so it won't start). The drop-in replacement is to use RedHat's podman. While I can add an alias to `.bashrc` and run the scripts with `bash -i` (to allow the aliases to work) this poses two problems:

- I need to modify the scripts to remove `sudo` from `sudo docker` 

- The alias doesn't seem to expand when the script calls other scripts. I get the error `timeout: failed to run command ‘docker’: No such file or directory`

Maybe replacing invocations of `docker` with something like `${DOCKER_COMMAND}` could work.

**Comment by coryan** [comment]
I think the `${DOCKER_COMMAND}` sounds like a good idea.

Inconveniently, we are in the middle of changing all the scripts in `ci/kokoro/*` to be generated from templates in the `google-cloud-cpp-common` repository.  For what it is worth, `ci/kokoro/readme` and `ci/kokoro/install` are done, the rest we have not even started on.

**Comment by devjgm** [comment]
We're already using fedora:31 in all of our builds. Has this issue been fixed or is it obsolete?

**Comment by coryan** [comment]
This is about running the scripts from Fedora:31, which invokes `docker`, that is, if your workstation is running Fedora:31 then saying `./ci/kokoro/docker/build.sh ubuntu` will not work because `docker` does not exist and you are supposed to use `podman` or something.

We no longer have developers using Fedora in their workstation, though.  We could close this and fix it if there is demand in the future.

**Comment by devjgm** [comment]
I see. Thanks. Since this issue only affects _developers_ (i.e., us and any contributors), and not our _customers_, then I say we close this and open (this or) a new issue if/when the need arises.
