### ISSUE TITLE
Parallel resumable upload corrupting uploads to GCS

### ISSUE THREAD

**Issue by anuptalwalkar** [googleapis/google-cloud-cpp#3280]
### Does this issue affect the `google-cloud-cpp` project?
Yes

### What component of `google-cloud-cpp` is this related to?
- Cloud Storage.

When resumable upload is used from 2 different hosts, client library is inconsistent in sending bytes upstream. Currently, next_expected_bytes is returned from the server as a response to content-range upload on resumable stream. If there are 2 clients uploading same object from 2 hosts, lagging stream gets the updated next_expected_byte. The client library does not support jump in the range bytes in the buffer, and sends incorrect byte range to the updated next_expected_byte. 

This results in - 
1. possible data corruption due to incorrect byte range sent from client. 
2. one of the stream sending more bytes than needed (since it is a jump in the next_expected_bytes, but not in the cached buffer data) resulting in inconsistent_data error from GCS. 

example scenario- for object with 1000 bytes:

1. stream 1 starts sending bytes 0-99, 100-199,.. 
2. stream 2 starts resumable uploads 500-599, 
3. stream 1 receives 503 bigtable_stale_version on 500-599
4. stream 1 uploads 500-599,600-699,700-799. 
5. from response to point 2, stream 2 receives next_expected byte 800 rather than 600. 
6. stream 2 sends (600-699) range data from its cached buffer to 800-899,
7. stream 1 is closed. 
8. stream 2 gets error inconsistent_data_size due to sending more bytes from cached buffer to GCS.

**Comment by Jseph** [comment]
Here are a few more details:

When an object write is resumed an instance of ObjectWriteStreambuf is returned. The user is expected to call [next_expected_byte()](https://github.com/googleapis/google-cloud-cpp/blob/ef65f6123d297a1289dc3ab846828f58c616e701/google/cloud/storage/internal/object_streambuf.h#L125-L127) on the stream to know where to start the upload.  The user is then expected to start at that offset and stream in all of the bytes they want to upload.

Occasionally the value for the next expected byte returned by GCS can jump. anuptalwalkar@ pointed out one way that this can happen. The [resumable upload documentation](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload) suggests there are other ways for this to happen 

> Use the Range header in the response to determine where to start the next chunk. Do not assume that the server received all bytes sent in the previous request.

The [CurlResumableUploadSession](https://github.com/googleapis/google-cloud-cpp/blob/ef65f6123d297a1289dc3ab846828f58c616e701/google/cloud/storage/internal/curl_resumable_upload_session.cc#L50-L65) implements this correctly. The next expected byte is always set based on the response from GCS.  Unfortunately the stream doesn't check to see if this value has jumped.  I think some logic should be added [here](https://github.com/googleapis/google-cloud-cpp/blob/ef65f6123d297a1289dc3ab846828f58c616e701/google/cloud/storage/internal/object_streambuf.cc#L378) to check if next_expected_byte corresponds to the next byte in the buffer.  If not the stream needs to be set to a bad state and the upload_session_ should probably be replaced with a `ResumableUploadSessionError` so that no further bytes can be uploaded.

**Comment by Jseph** [comment]
I'll write up a fix for this.

**Comment by mr-salty** [comment]
I will hold the release for this PR if you expect to have it done in the next couple days (I'd like to cut a release this week and I'm OOO on Friday)... otherwise we can do a .1 release
