### ISSUE TITLE
Enhance the GCS testbench to support binary data

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3301]
The GCS testbench does not work with binary data, forcing us to run any tests with binary data against the production environment.

**Comment by remyabel** [comment]
It chokes at `body.find(marker)` presumably because the binary data consists of non-representable characters. Some ideas:

- Search the body manually for the boundaries
- Encode the binary data in base64, then decode it after we find the boundaries
- Use [email.contentmanager](https://docs.python.org/3.6/library/email.contentmanager.html#module-email.contentmanager)

The last option seems to be the best unless there's some disadvantage I'm missing.

**Comment by remyabel** [comment]
Using `email.parser.Parser().parsestr` runs into the exact same problem as before where it tries to decode the binary data. Using `email.parser.BytesFeedParser` would probably work, but that's only in Python 3.

@crwilcox Any progress on your Python 3 PR?

**Comment by vnvo2409** [comment]
I don't understand clearly this issue. Could you explain it to me ? @coryan 
I think we could add this feature to the new emulator as well.

**Comment by coryan** [comment]
The testbench treats some of the inputs uploaded by the application as strings, which produced problems.

For example, when uploading a binary blob using multipart uploads we put everything into a giant blob, and then split it using the MIME separator.  Used to be the case (maybe still is) that Python did not like to do that if the payload was binary.

**Comment by vnvo2409** [comment]
I am not sure I am understand what you mean ( I don't have much experience with network programming indeed ). However, If I comment this line, the test still passes so I think it we could close this issue.
https://github.com/googleapis/google-cloud-cpp/blob/7293cf2ff7b54d10d20a8aedced98b6026b63453/google/cloud/storage/tests/object_integration_test.cc#L268-L270

**Comment by coryan** [comment]
Confirmed that the emulator supports binary data correctly. Adding a new integration test in #5508.
