### ISSUE TITLE
Question: how to generate and use AuthorizedUser wrt CreateAuthorizedUserCredentialsFromJsonFilePath

### ISSUE THREAD

**Issue by yxiang92128** [googleapis/google-cloud-cpp#3481]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?

Yes, stuck at using the API CreateAuthorizedUserCredentialsFromJsonContents or CreateAuthorizedUserCredentialsFromJsonFilePath

### What component of `google-cloud-cpp` is this related to?

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?
 latest HEAD git rev-parse HEAD
66cb4f9f5b4b6f18ba222cd44f9287ff25571260

### What compiler and version are you using?
gcc-5.3.1

Please include the output of `g++ -v` or the equivalent command-line flag.
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/5/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,fortran,ada,go --enable-checking=release --with-gxx-include-dir=/usr/include/c++/5 --enable-ssp --disable-libssp --disable-libvtv --enable-libmpx --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --with-default-libstdcxx-abi=gcc4-compatible --enable-version-specific-runtime-libs --enable-linker-build-id --enable-linux-futex --program-suffix=-5 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 5.3.1 20160301 [gcc-5-branch revision 233849] (SUSE Linux)
### What operating system and version are you using?
SLES12SP3
If you are using a Linux distribution include the name and version of the
distribution too.

### What were you trying to do?
I am trying to write up an app using End User authentication scheme only. So I created a bucket under the user's storage account and  I generated a OAuth Client ID and Key under Cloud Console -> APIs & Services -> Cloud Storage with type "Other".  Then I added that OAuth Client ID as Members for that bucket and authorized it to be "Storage Admin". 

Within my google-cloud-cpp application,  I've constructed a json contents string with client_id, client_secret as follows (XXXX and YYY are actual strings from the OAuth output json file):
std::string const AUTHORIZED_USER_VALID2_CRED_CONTENTS = R"""({
  "client_id": "<XXXXXXXXXXXXXX>.apps.googleusercontent.com",
  "client_secret": "<YYYYYYYYY>",
  "refresh_token": "https://oauth2.googleapis.com/token",
  "type": "authorized_user"
})""";

Then I passed it to 
  auto creds_json = gcs::oauth2::CreateAuthorizedUserCredentialsFromJsonContents(AUTHORIZED_USER_VALID_CRED_CONTENTS);
  Client client(*creds_json);
### What did you expect to see?
I expect the client to be constructed and list-objects, read-object operation should return OK

What's the proper way to write an app with only End User authentication?  And how do you actually configure an end user to have access to a bucket and also obtain the JSON file containing the correct credentials I could use to call CreateAuthorizedUserCredentialsFromJsonFilePath with?

### What did you see instead?
Instead I see the following errors:
Storage Client Credential creation, status= [OK]
Standard C++ exception raised: Permanent error in ListObjects: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} [INVALID_ARGUMENT]

### Anything else you would like us to know?
Using a service account Json file, it seems to be working.

Include here information about your environment that is not captured above, or
any other information you think might be relevant.

**Comment by coryan** [comment]
> ### What were you trying to do?
> I am trying to write up an app using End User authentication scheme only.

Since I am no expert in OAuth 2.0 let me make sure I understand what that means: you have an application that needs to access GCS **on behalf of** some user, and therefore you want the application to use an [access token]() for that user when talking to GCS.  Is that accurate?

> So I created a bucket under the user's storage account and I generated a OAuth Client ID and Key under Cloud Console -> APIs & Services -> Cloud Storage with type "Other". Then I added that OAuth Client ID as Members for that bucket and authorized it to be "Storage Admin".

I am not sure I follow:

- Did you add those members as what?  `serviceAccount:blah-blah` ? `user:blah-blah`?
- If you are going to authenticate as the end-user, why grant your "application" (or Client ID) access to the Bucket?

> 
> Within my google-cloud-cpp application, I've constructed a json contents string with client_id, client_secret as follows (XXXX and YYY are actual strings from the OAuth output json file):
> std::string const AUTHORIZED_USER_VALID2_CRED_CONTENTS = R"""({
> "client_id": ".apps.googleusercontent.com",
> "client_secret": "",
> "refresh_token": "https://oauth2.googleapis.com/token",

This should be an actual token that you obtained via the OAuth flow.  

> "type": "authorized_user"
> })""";

I do not see XXXX or YYYY here, presumably those are (part of) the `client_id` and `client_secret` values?

> 
> ### What did you expect to see?
> I expect the client to be constructed and list-objects, read-object operation should return OK

That seems reasonable.

> 
> What's the proper way to write an app with only End User authentication?

AFAIK, you just create the JSON file (or contents) with the secret and refresh token from the user and you are good to go.  It is different if you want to act on behalf of the user but using your client id. Then you need to go through the OAuth flow to get an **access** token given your client ID and then end-user authorization code. And then present that access token to GCS. 

> And how do you actually configure an end user to have access to a bucket and also obtain the JSON file containing the correct credentials I could use to call CreateAuthorizedUserCredentialsFromJsonFilePath with?

If you are asking about how to get a refresh token and secret for a user that is a bit beyond the scope of the GCS client library.  You need to follow one of the OAuth flows for that.

> 
> ### What did you see instead?
> Instead I see the following errors:
> Storage Client Credential creation, status= [OK]
> Standard C++ exception raised: Permanent error in ListObjects: {
> "error": "invalid_grant",
> "error_description": "Bad Request"
> } [INVALID_ARGUMENT]

Ack.  That looks like the OAuth server rejecting the request to convert what (should be) a refresh token into an access token.

> 
> ### Anything else you would like us to know?
> Using a service account Json file, it seems to be working.

Okay, that is good news.

Have you tried to use this with your *own* account?  For example, use `gcloud auth application-default login` will create a valid authorized user credentials file in `$HOME/.config/gcloud/application_default_credentials.json`.  I have good reason to believe it works, but I use these all the time.

It is possible that this is not what you need, but maybe it can help us clarify any misconceptions I may have.

**Comment by yxiang92128** [comment]
the "gcloud auth application-default login" trick did the work!! Thanks.
