### ISSUE TITLE
Enable integration tests on Windows and Mac

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3540]
Make sure test coverage is similar (e.g. -cpp does not run integration tests for Windows or macOS, while -spanner does).

**Comment by devjgm** [comment]
The test coverage for all repos is currently similar, between 93% (`-cpp) - 97% (`-pubsub`). So merging these repos we'll likely end up somewhere around 95%.

![coverage](https://user-images.githubusercontent.com/9447643/78923405-2852f680-7a66-11ea-985e-41d3824e67ae.png)

Is that all we wanted to confirm with this issue, or is there more? I'm wondering if this issue is now done?

**Comment by coryan** [comment]
No, see the description.

* We do not run any of the integration tests on Windows, they "should" work, but  how do we know?
* We do not run any integration tests on macOS either.  How do we know the code works?
* We do not run the integration tests with any of the sanitizers, there may be bugs we are missing because the unit tests do not provide nearly the same coverage.

In `-spanner` we do run the integration tests and samples for Windows and macOS and with the sanitizers. I do not think we want to lose that coverage as we move the code to `-cpp`.

**Comment by devjgm** [comment]
I see. OK. So I think i'll re-title this issue "Enable integration tests on Windows and Mac"... done. If I've misunderstood (again) that's a bad title, let me know and I'll fix it.
