### ISSUE TITLE
Enable ccache for clang-3.8 build in -spanner

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3610]
`google-cloud-cpp-spanner` does not build with clang-3.8 and ccache enabled. That is not a major problem for a single repository, but would become a problem when building in the mono repo.

We should fix this before moving the `-spanner` code to `google-cloud-cpp`.

**Comment by devjgm** [comment]
Is this something we need to fix in `-spanner`, or would this be magically fixed when `-spanner` moves to `-cpp` due to the fact that the `-cpp` builds already use ccache?

**Comment by coryan** [comment]
In `-spanner`. Building with ccache and clang-3.8 does not work in `-spanner`. I think the preprocessor gets confused with one of our `R"""()"""` strings.  At the time I simply turned off ccache because it was not that critical.

When we import the code the build would break again, and now ccache is more important.

**Comment by devjgm** [comment]
Moved this to the "move google-cloud-cpp-spanner" milestone because it seems more related to that. For example, rather than enabling ccache in the spanner repo now, we could potentially just discover any ccache-related issues when we're doing a "dry-run" import of spanner in `-cpp`, and fix it at that point. I imagine this may not be the only issue that shows up when we do the first build in `-cpp` after copying the files over.
