### ISSUE TITLE
Update BigQuery protos to `v1/` version.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3776]
Currently using `v1beta1/` .

**Comment by devjgm** [comment]
This would be easiest to do after we move the googleapis/cpp-cmakefiles into this repo. Otherwise, we'll have to update that repo first ([here](https://github.com/googleapis/cpp-cmakefiles/blob/7f63ce19f72cab66849e56011efb94ddb263fea8/CMakeLists.txt#L77)), do a release, update vcpkg, then update the code here.

This isn't urgent. Waiting seems fine to me.

**Comment by devjgm** [comment]
There are non-trivial differences between [v1beta1](https://github.com/googleapis/googleapis/tree/master/google/cloud/bigquery/storage/v1beta1) and [v1](https://github.com/googleapis/googleapis/tree/master/google/cloud/bigquery/storage/v1) that require changes to the actual code. This is not a simple upgrade of the protos used. And there's no urgency or need to do this update until we're working toward a BigQuery GA.

This can be done sometime later when we're really working on bigquery. I don't think this needs to be part of the "Monorepo: Final Cleanup" milestone.

I also think we should probably just close this issue, because we don't need it to remind us to do anything. When we start working on pushing BigQuery toward a GA launch, switching from the v1beta1 protos will be an obvious step that we won't really be able to forget. It will become a work item in the milestone used to track moving BigQuery to GA. So in an effort to keep our issues somewhat clean, I'm going to close this.
