### ISSUE TITLE
docs for those of us who don't use bazel or cmake

### ISSUE THREAD

**Issue by willie** [googleapis/google-cloud-cpp#3967]
**What component of `google-cloud-cpp` is this feature request for?**
Cloud Storage

**Is your feature request related to a problem? Please describe.**
I don't use bazel or cmake; I use Xcode and GYP (to generate makefiles), so I don't know what files are important or not important to build.

**Describe the solution you'd like**
I'd like documentation on what files are expected, what preprocessor constants are expected, and what libraries are needed, to build this with another build system. 

Example: 
you need the following directories, you need to define these constants, you should link against these libraries

**Describe alternatives you've considered**
I tried reading the build system documents (for the previous version of this library) and I found it easier to understand to wrap the Go library in a c-archive and call it from C++, but I'd like to use a C++ native library.

**Additional context**
I'm sorry if this comes across as grumpy.

**Comment by coryan** [comment]
> **Is your feature request related to a problem? Please describe.**
> I don't use bazel or cmake; I use Xcode and GYP (to generate makefiles), so I don't know what files are important or not important to build.

Ack, bear with me because I am not familiar with either.

- Would it work for you to *install* (maybe in `$HOME/local`) the libraries using CMake and then use the libraries at that location?
- Are GYP / Xcode able to use libraries once installed or to call out to an external build tool (maybe that is what you call a c-archive)?

> **Describe the solution you'd like**
> I'd like documentation on what files are expected, what preprocessor constants are expected, and what libraries are needed, to build this with another build system.

That is likely to be out of date pretty easily.  But maybe this helps: the list of `*.h` and `*.cc` files for each library are kept in generated `*.bzl` files, for example here are the files you need for the storage client:

https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/storage_client.bzl

In general I do not think we pass any `-D` flags to the libraries when we compile them, at least not by default.  As to compilation flags, those vary depending on how you build, e.g., you can build with or without `-O2`.  I am not sure there is an "easy" way to figure those out other than compile with CMake and use something like `cmake --build binary-dir -- VERBOSE=1` to see the command-line.

The dependencies are not captured in an easy file. But in the case of the storage library you need the `google-cloud-cpp` common library (which has a similar `.bzl` file), `libcurl`, `crc32c`, and an implementation of OpenSSL (we test with libressl on macOS for what it is worth).

Does that help you get started?

**Comment by willie** [comment]
I can try and build the libraries using CMake and then see if I can statically link the library to my Xcode project (like I do with Go's build for `c-archive` does). What are the expectations around headers? I guess I can just put the repo in the entire path. I'll try that. I'll come back with more questions.

(FWIW, GYP is the build tool that Google built for Chromium, then abandoned, then the node community picked up. It generates build projects for various build systems via generators. It's nice.)

**Comment by willie** [comment]
What `cmake` command and where in the directory hierarchy should I run to build a static library?

**Comment by coryan** [comment]
> (FWIW, GYP is the build tool that Google built for Chromium, then abandoned, then the node community picked up. It generates build projects for various build systems via generators. It's nice.)

Of course is was a tool that Google created, that is why I never heard about it :joy:   That reminds me, CMake can generate XCode projects, though I have never tried that myself:

https://cmake.org/cmake/help/latest/generator/Xcode.html
https://stackoverflow.com/questions/16700415/cmake-generate-xcode-project-from-existing-sources/16701018

> What `cmake` command and where in the directory hierarchy should I run to build a static library?

Assuming you want `google-cloud-cpp` to download and install its dependencies [1], then this is what I usually use on macOS:

```
brew install libressl  # The one dependency we don't build ourselves
export OPENSSL_ROOT_DIR=/usr/local/opt/libressl
cmake -Hsuper -B.build -DGOOGLE_CLOUD_CPP_EXTERNAL_PREFIX=$HOME/my-local
cmake --build .build
```

That will put all the `.a` files in`$HOME/my-local/lib` and all the includes in `$HOME/my-local/include`.  If you prefer to put them in `/usr/local` just change the value of `GOOGLE_CLOUD_CPP_EXTERNAL_PREFIX`.

[1]: Which may not be what you want, e.g. maybe you want to use your own version of `libcurl`, or `protobuf`, or disable the libraries you do not use, but it is easier to explain this way, and we can build on this later.
