### ISSUE TITLE
Automatically clean up the old leaked databases

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp#4033]
We automatically delete old leaked instances at:
https://github.com/googleapis/google-cloud-cpp-spanner/blob/6e82ef3f1f2c87c5894f851d344e04bf2bfc1fd0/google/cloud/spanner/integration_tests/instance_admin_integration_test.cc#L63

We can do similar thing for leaked databases too.

**Comment by devjgm** [comment]
I this this issue was accidentally fixed by https://github.com/googleapis/google-cloud-cpp-spanner/pull/1486/commits/1221e11df29d8bd789050925d015379b7eaee2d7. In that commit all of our integration tests started subclassing `spanner_testing::DatabaseIntegrationTest`, and that base class cleans up its databases rather than leaking them.

https://github.com/googleapis/google-cloud-cpp/blob/971d2b2f7cb4b93a4b1f5463f88382d58e6188a6/google/cloud/spanner/testing/database_integration_test.cc#L85-L89

If I'm mistaken and this is still an issue, we can reopen.

**Comment by coryan** [comment]
TearDownTestSuite() does not run on a crash, so we can still be leaking databases.  The idea is to find if there are old, unused databases at the beginning of the test and remove those, because that is robust even if the test crashes.
