### ISSUE TITLE
[Flake]: Bazel builds failed while downloading http archive.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4045]
Two (otherwise unrelated) builds failed while downloading the BoringSSL archive:

https://sponge.corp.google.com/target?id=936c747b-c24b-4938-bb80-108e46618629&target=cloud-cpp%2Fspanner%2Fdocker%2Fubsan-presubmit

https://source.cloud.google.com/results/invocations/2340826a-9f4e-4277-a244-0bbacbbb84aa/targets/cloud-cpp%2Fspanner%2Fmacos%2Fbazel/log

We should consider caching the most important tarballs in GCS so the download has an alternative location. I believe the TensorFlow folks do this:

https://github.com/tensorflow/tensorflow/blob/76aa7f81ab726eb9f862c6c691ef2c76ea4e6af3/WORKSPACE#L10

**Comment by coryan** [comment]
These are still happening, but maybe just on indirect dependencies, the latest example is:

https://source.cloud.google.com/results/invocations/82c4e4a9-4cde-4f1c-b637-28d8f81feb42/targets

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/d77fd19f-24ea-46c0-a3c1-da34656f63be

**Comment by devjgm** [comment]
That last one looks like general networking issues to me. bazel failed to fetch everything. I filed https://github.com/bazelbuild/bazel/issues/11520 for the heck of it.

**Comment by devjgm** [comment]
The error in https://github.com/googleapis/google-cloud-cpp/issues/4045#issuecomment-625820538 is from a Windows build. There are a bunch of errors from bazel, but I suspect they all stem from the same issue. I suspect the problem was

```
2020-04-15T13:17:05.7816072+00:00  extracting build cache failed with exit code 2.
```
So perhaps we left the build cache directory in some weird state, that bazel then tried to use, and the cached files were corrupt somehow.

I suspect the fix for this is to clear out the build cache directory if extracting the cache fails. I'll see if I can figure out how to do "rm -rf <dir>" in powershell :-)

**Comment by coryan** [comment]
> The error in [#4045 (comment)](https://github.com/googleapis/google-cloud-cpp/issues/4045#issuecomment-625820538) is from a Windows build. There are a bunch of errors from bazel, but I suspect they all stem from the same issue. I suspect the problem was
> 
> ```
> 2020-04-15T13:17:05.7816072+00:00  extracting build cache failed with exit code 2.
> ```

I think that happens on all builds.

> 
> So perhaps we left the build cache directory in some weird state, that bazel then tried to use, and the cached files were corrupt somehow.

As I recall, it is the weird links that make the cache extraction unhappy. Which could be masking a real error, of course.

> 
> I suspect the fix for this is to clear out the build cache directory if extracting the cache fails. I'll see if I can figure out how to do "rm -rf " in powershell :-)

We probably do one of those at the end of the build... `Remove-Item` is the magic word I believe.

**Comment by devjgm** [comment]
I think you're right that these errors happen even on successful builds. Here's a log of a successful build that shows the same error extracting the build cache. https://source.cloud.google.com/results/invocations/47c78875-1fb0-4753-aef9-cf1765f2b197/targets

So I suppose on all of these builds the log says:

```
20-06-05T16:55:55.1958683+00:00  extracting build cache failed with exit code 2.
2020-06-05T16:55:55.1958683+00:00  Continue building without a cache
```

When it continues with all/most of the cache intact. Which means that if I `Remove-Item` the cache directory on a failed cache extraction, that'd happen on all builds, and we'd effectively never use the cache.

However, I still suspect that the [errors in this build log](https://source.cloud.google.com/results/invocations/82c4e4a9-4cde-4f1c-b637-28d8f81feb42/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fquickstart-bazel-presubmit/log) are due to a corrupt bazel installation, which _seems_ like it could be caused by a corrupt cache extraction.

Perhaps there's some way to make it so that our `7z` extractions are _successful_ most of the time.

**Comment by coryan** [comment]
Maybe we should not store those unsafe links in the first place.

**Comment by devjgm** [comment]
We use the `-snl` flag to `7z`, which says to preserve symbolic links.

https://github.com/googleapis/google-cloud-cpp/blob/f25fcba465bb9f21bb1dc8705a0b2036865d3fe7/ci/kokoro/windows/build-quickstart-bazel.ps1#L85-L86

Maybe we should just remove those flags? Maybe I'll try that change and see what a draft PR does.

**Comment by coryan** [comment]
I am not sure if there is a mix of safe and unsafe symbolic links in the Bazel cache. Or even if the symbolic links are necessary. Only one way to find out I guess.

**Comment by devjgm** [comment]
OK, after that last PR (#4355) where I stopped preserving symlinks, here's a build log:

https://source.cloud.google.com/results/invocations/de3afdb3-b089-411f-828c-d78b61e20891/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fquickstart-bazel-presubmit/log

This build log looks pretty clean. It does not show the error about the "Dangerous" links. And the extraction of the cache step succeeded instead of exiting with "error 2" as they previously did.

So, I don't know if this will _fix_ anything, but it may expose an error if we continue to see these flakes.

**Comment by coryan** [comment]
At the same time this started happening:

https://source.cloud.google.com/results/invocations/6cc3d1b6-3c2e-46ad-bc8a-6f183a577c82

The Windows+Bazel build has been broken since then. Please take a look when you get a chance.

**Comment by coryan** [comment]
The builds timeout after 180m, so it might be unrelated or a separate problem, but I think they are timing out trying to recreate the bazel cache tarball.

**Comment by devjgm** [comment]
ok, I'm rolling back my PR. It didn't help and broke something.

**Comment by coryan** [comment]
Here is a different case:

https://source.cloud.google.com/results/invocations/64877f12-5243-4419-ab09-6e31b3562ff9

I believe our retry loop is probably too fast, or needs some kind of cleanup in between retries, trying a couple of minutes later worked.

**Comment by devjgm** [comment]
> Here is a different case:
> 
> https://source.cloud.google.com/results/invocations/64877f12-5243-4419-ab09-6e31b3562ff9
> 
> I believe our retry loop is probably too fast, or needs some kind of cleanup in between retries, trying a couple of minutes later worked.

I've split this issue out into https://github.com/googleapis/google-cloud-cpp/issues/4861.

**Comment by coryan** [comment]
Now that #5346 is merged I think we should close this. The last "repeat" is from 2020-07-02, so more that 90 days anyway.
