### ISSUE TITLE
add BackoffPolicy and RetryPolicy to google::cloud common namespace

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#4071]
Additionally refactor service libraries (bigtable, spanner, etc.) to use these classes as appropriate.

**Comment by coryan** [comment]
Can you say more words?  These classes already exist  in `google/cloud/internal/`:

https://github.com/googleapis/google-cloud-cpp/blob/5d4c13e4c2279cd2f97e31aa155d40743c516113/google/cloud/internal/backoff_policy.h#L47

https://github.com/googleapis/google-cloud-cpp/blob/5d4c13e4c2279cd2f97e31aa155d40743c516113/google/cloud/internal/retry_policy.h#L34

The retry policy is not public because (so far) each service seems to have its own definition of what is a transient error, and we cannot reuse them across services.  There are other (now mostly historical) reasons, such as the different API for the Bigtable policies.
