### ISSUE TITLE
Provide rvalue-ref overloads for `Row` accessors

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#4107]
This is needed in order to allow for passing the underlying data by move rather than by cref, which usually implies copying.

**Comment by devjgm** [comment]
One concern with having objects with rvalue overloaded accessors is that the caller can really only use  one of them, because using a second one would require using a moved-from object. For example:

```cc
struct A {
  X&& f() &&;
  Y&& g() &&;
};

A a;
auto x = std::move(a).f();  // OK
auto y = std::move(a).g();  // Oops: `a` has already been moved.
```

Of course, depending on the implementation of `A`, it might actually be safe. Though, I suspect there will be some clang-tidy checkers that warn on this usage.

I'd be concerned that this might lead to an easily misused API.

WDYT?

**Comment by devjgm** [comment]
Oops. I see that @coryan already commented about this exact concern in the PRs. I missed that. You can disregard this since Carlos already started that discussion before me.
