### ISSUE TITLE
Followup on read_offset off-by-one behavior

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4233]
Asked the GCS team if we are really supposed to has for "-(N + 1)" bytes to get the last N bytes.

**Comment by coryan** [comment]
Tracked internally at b/157011756

**Comment by devbww** [comment]
I'm now _guessing_ this this is intentional, and largely because `0 == -0`.

That is, given that the call is to set the read offset, and that there is no lseek(2)-like "whence" parameter, the use of negative values to represent "from end" pretty much requires the "+1" behavior.  `set_read_offset(0)` is before first byte, and `set_read_offset(-1)` is after last byte.

**Comment by coryan** [comment]
I am going to close this.  The documented behavior for `-N` is "read last N bytes", I confirmed with the GCS folks that it was their intention for this to be so. @devbww if you change their minds we will need to change our code, but so far it seems everything is working-as-intended.
