### ISSUE TITLE
Automatically update proto library interdependencies

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4248]
We have to manually declare the dependencies between the proto libraries. It would be nice to automate this.  A start is the following script:

```
# protos=(... list of proto files ...)
for proto in "${protos[@]}"; do (cd cmake-build-debug/external/googleapis/src/googleapis_download; grep -H '^import ' "${proto}" | grep -v google/protobuf); done | sed -e 's;google/;;g' -e 's/:import "/ /' -e 's/";//' -e 's;/;_;g' -e 's/\.proto/_protos/g' | sort
```

**Comment by devbww** [comment]
This is deemed fixed by the combination of #7643, #7650, #8792, and #8809.  The CMake proto files and dependencies are now all sourced from the `external/googleapis/protolists/*.list` and `external/googleapis/protodeps/*.deps` files, which are maintained by the `external/googleapis/update_libraries.sh` script.
