### ISSUE TITLE
[Flake] Windows+CMake quickstart build failed

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4253]
I have never seen this before, and the change is unrelated, so I expect flakiness:

https://source.cloud.google.com/results/invocations/93cd9bb6-fd25-47b4-84a7-e0364e6292b8

```
2020-05-21T12:54:19.7925660+00:00  Running quickstart for bigtable
Getting a single row by row key:cf1:greeting    @ 1585942567265000us
"Hello"
quickstart test for bigtable failed with exit code -1073741819.
Build failed with exit code 1
```

I have made no attempts to root cause this.

**Comment by coryan** [comment]
It just repeated:

https://source.cloud.google.com/results/invocations/f49eaf00-0060-49e2-98a3-5cd4b3c14b94

**Comment by devjgm** [comment]
The exit code `-1073741819` is `0xc0000005` in hex, which appears to be a Application Error 0xc0000005 (Access Violation) on Windows.

From glancing around docs, I see mentions of this being caused by anti-virus software, memory corruptions, corrupt system files, corrupt visual studio install, etc.

I wonder if maybe somethings broken w/ our Windows image? Or maybe some type of software update happened while our test was running (can that happen?).

**Comment by devjgm** [comment]
Another: https://source.cloud.google.com/results/invocations/1957e7e3-bd76-4754-90ee-933d3c689b4e/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fquickstart-cmake-static-presubmit/log

**Comment by coryan** [comment]
> I wonder if maybe somethings broken w/ our Windows image? Or maybe some type of software update happened while our test was running (can that happen?).

I suspect it might be another manifestation of #3933. gRPC's cleanup code crashes on shutdown sometimes, and the log shows the program was shutting down when it crashed.

I will try to repro this, but I think we will end up marking as a duplicate.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/82f385f7-c2fd-4e72-ae14-e26e52f19c4b

**Comment by coryan** [comment]
Okay, I just ran this on my VM and got the same crashes I was getting with #3933. Closing as a duplicate.
