### ISSUE TITLE
Opening a Spanner database should prepare some sessions

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4483]
Internal: http://b/114104423

**Comment by mr-salty** [comment]
In essence, the proposal here is to default [`SessionPoolOptions::min_sessions_`](https://github.com/googleapis/google-cloud-cpp/blob/3a03329beebb5f173b2eef4809b6829e5af8b1e4/google/cloud/spanner/session_pool_options.h#L150) to 100 instead of 0, so constructing a `Connection` eagerly creates 100 sessions (spread across channels).

However, doing that causes unit tests to fail due to mock expectations, so they need to be updated... it's slightly tricky since the `Session` creation is asynchronous.

**Comment by devbww** [comment]
Leaving this open to tie to http://b/114104423 (and http://b/160800438).
