### ISSUE TITLE
[flake] ClientStressTest.UpsertAndSelect Expected: (total.failure_count) <= (experiments_count * 0.001)

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4759]
seen once on 2020-07-28 in a tsan build [log](https://source.cloud.google.com/results/invocations/4007c60d-a8b6-4c87-a372-f9f243db0eea/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Ftsan/log)

note the expectation is for 0.992 failures and we saw 1, seems a bit fishy.

```
[2,723 / 2,727] 7 / 12 tests, 1 failed; Testing //google/cloud/spanner/benchmarks:multiple_rows_cpu_benchmark; 51s processwrapper-sandbox ... (4 actions running)
INFO: From Testing //google/cloud/spanner/integration_tests:client_stress_test:
==================== Test output for //google/cloud/spanner/integration_tests:client_stress_test:
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from ClientStressTest
Creating database and table ..........DONE
[ RUN      ] ClientStressTest.UpsertAndSelect
google/cloud/spanner/integration_tests/client_stress_test.cc:125: Failure
Expected: (total.failure_count) <= (experiments_count * 0.001), actual: 1 vs 0.992
[  FAILED  ] ClientStressTest.UpsertAndSelect (5085 ms)
[ RUN      ] ClientStressTest.UpsertAndRead
[       OK ] ClientStressTest.UpsertAndRead (5325 ms)
[----------] 2 tests from ClientStressTest (10410 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (23200 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ClientStressTest.UpsertAndSelect

 1 FAILED TEST
```

**Comment by coryan** [comment]
First an observation about what this means: even with the transaction restart loop we had one transaction failure in about 1,000 different transactions.  That seems high, I would expect a *much* **much** lower failure rate, maybe one failure in a billion.

> note the expectation is for 0.992 failures and we saw 1, seems a bit fishy.

I agree that it is fishy.  We should run far more iterations [*] and still expect less than 1 failure.  That is to say, even though this test is underpowered to detect problems reliably (it has too many false negatives), the fact that it detected *a* problem is an indication that we do have a true positive (failure) in the test.




[*]: how many iterations is an statistical power question, maybe enough so we detect a problem with more than 95% probability?

**Comment by devbww** [comment]
> We should run far more iterations and still expect less than 1 failure.

Irrespective of how many iterations we expect to produce a single failure (currently 1000), it seems to me that we're currently just expecting one too few.  That is, we should allow one failure in the first (up to) N iterations, an additional failure in the next N iterations, etc.

At the moment we expect zero failures in the first 1000 iterations, and, if errors are possible, that doesn't seem very tolerant.  That is, even if we expect a 0.1% failure rate, we should never expect zero failures.  Fortunately, we usually run more than 1000 iterations, which allows for at least one error.

But, in the case of this TSan run, it seems we only got 992 iterations in the allowed 5 seconds, and that means a single failure caused the test to fail.

We could ensure that we always run a (positive) multiple of N iterations, but instead I'll send a [PR](https://github.com/googleapis/google-cloud-cpp/pull/4989) that just does the "+ 1" and we'll see what people think.  We might also discuss what "N" should be, if not 1000.

**Comment by coryan** [comment]
So, I am going to go on tangents for a second. 

- This test was written to fix googleapis/google-cloud-cpp-spanner#455, its purpose is to verify the library does not "crumble" when used by multiple threads doing work.
- I think we should expect that the library has a very low error rate under "normal" conditions [1].
- For me, "very low" should be in the less than one library-induced failure per billion requests [2].
- For me, "crumble" would mean "many more errors than normal", so maybe 1 error per thousand requests indicates "crumble".

I believe we should tune this test to confidently [3] detect if the expected failure rate [4] is really below that 1 / 10^9 threshold.

This is an statistics question, left as an exercise to the reader.  Hint:

https://github.com/googleapis/google-cloud-cpp/blob/e82cb58002dfa9031396c881e2414d13aceb21b2/google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test.cc#L147-L163

[1]: "normal" here is intended to excluded the network being down hard, your instance being overloaded for hours, your client being overloaded and unable to make progress, trying to make requests that fail because they are malformed, etc.  It is not intended to exclude things like "your transaction was aborted", or "you had a few network glitches / DNS resolution problems".
[2]: I expect a production application at  10,000 qps  to see less than one failure per week, that is about once every 6 billion requests.
[3]: "confidently" is typically operationalized as "the probability of correctly detecting the failure when the failure is present is > 0.80, and the probability of erroneously claiming a failure when the failure is not present is < 0.05". Both numbers are arbitrary and can be made more strict at the cost of more testing.
[4]: typically you cannot assert "we measure the failure rate to be X", but rather "we estimated the failure rate to be within this range with 95% confidence"... as long as the whole range is below your threshold you are Okay.

**Comment by devbww** [comment]
Reopening to address coryan@'s comment of 2020-08-31.

**Comment by coryan** [comment]
Moving the discussion to #4991, I think you fixed the flake. The question of whether the test is "good enough" should have been in a separate bug, my bad.
