### ISSUE TITLE
Consider using SFINAE for g::c::i::ComparePaginationValues()

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4814]
@devjgm [suggested](https://github.com/googleapis/google-cloud-cpp/pull/4806#pullrequestreview-462736826)

(optional): I might have written this overload sfinae'ing on the existence of `==`. Maybe like:

```cc
template <typename T>
auto ComparePaginationValues(T const& a, T const& b) -> decltype(a == b) {
return a == b;
}
```

Not sure which way is really "preferred", but something for you to consider. Happy with whatever you decide.

**Comment by devjgm** [comment]
To flesh out my suggestion a little, the question is *what* to SFINAE on: the existence of `op==`, or that `T` is not a subclass of `Message`. Since this overload of `ComparePaginationValues()` *is implemented* by calling `op==` on the two arguments, it makes sense that we'd SFINAE on the existence of this operator as well.

The difference with the existing implementation of 

```cc
template <typename T, typename std::enable_if<
                          !std::is_base_of<google::protobuf::Message, T>::value,
                          int>::type = 0>
bool ComparePaginationValues(T const& lhs, T const& rhs) {
  return lhs == rhs;
}
```

is that the existing implementation advertises that it works for any `T` that is not a subclass of `google::protobuf::Message`, but it actually requires that the `T` supports `op==`.

These are both part of an internal overload set, so whether we change anything or not is not a high priority, IMO. I just wanted to clarify my suggestion since it's in a longer-living issue now.

**Comment by devjgm** [comment]
Obsolete. This code no longer exits. 

Related to https://github.com/googleapis/google-cloud-cpp/pull/5545
