### ISSUE TITLE
The functions GoogleDefaultCredentials and CreateServiceAccountCredentialsFromDefaultPaths cannot use ADC created by gcloud from Google Cloud SDK

### ISSUE THREAD

**Issue by dpoloyko-epam** [googleapis/google-cloud-cpp#5028]
Both of them calls MaybeLoadCredsFromAdcPaths which tries to find a file application_default_credentials.json in ~/.config/gcloud directory. On the other hand gcloud utility provided by Google Cloud SDK stores this information inside credentials database in the same directory using SQLite. So C++ applications cannot pick up ADC created by gcloud command.

**Comment by coryan** [comment]
I am no expert on this, but I will try to explain what is going on. The "credentials database" is for `gcloud` to use, and only `gcloud`.  For development and "client library authentication" you want `gcloud auth application-default login`:

https://cloud.google.com/sdk/gcloud/reference/auth/application-default
https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login

That will create the file loaded by the client libraries.

> So C++ applications cannot pick up ADC created by gcloud command.

It depends what you mean by "created by gcloud command". If you mean "created by `gcloud auth login`" then yes, you are correct, and that is intentional. If you mean "created by `gcloud auth application-default login`" then that would be a bug, but I just tested.

Note that these credentials in `$HOME/.config/gcloud` are only recommended for development. For production you should either set the `GOOGLE_APPLICATION_CREDENTIALS` or the default service account for your environment (if available):

https://cloud.google.com/docs/authentication/production#automatically

**Comment by dpoloyko-epam** [comment]
I'm using "gcloud auth activate-service-account" and passing json file to it like that:
gcloud auth activate-service-account --key-file my-service-account.json

You are right, according to
https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account
it behaves like "gcloud auth login", not "gcloud auth application-default login".

After I activated service account or logged by "gcloud auth login" I can use gcloud without passing credentials. Is there any approach to get such credentials using google-cloud-cpp? It may be useful in case of users expects the behavior similar to gcloud when running console utility written on C++.

**Comment by coryan** [comment]
> I'm using "gcloud auth activate-service-account" and passing json file to it like that:
> gcloud auth activate-service-account --key-file my-service-account.json

> After I activated service account or logged by "gcloud auth login" I can use gcloud without passing credentials.

Okay.

> Is there any approach to get such credentials using google-cloud-cpp?

If you have the `my-service-account.json` file you can set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable pointing to the full path of that file.  The library will load the file and use those credentials to authenticate.

> It may be useful in case of users expects the behavior similar to gcloud when running console utility written on C++.

I agree it would be less surprising if the libraries used the gcloud credentials. There are downsides:

- it introduce dependencies that application developers may not want (sqlite for example)
- it may steer application developers towards the wrong path: the expectation is that most applications developed with the client libraries are servers or batch jobs (i.e., not command-line tools), they typically run in environments where `$HOME`, or `gcloud` do not even exist.

**Comment by dpoloyko-epam** [comment]
Agree that implementing this API will require SQLite and introduction of yet another function in addition to GoogleDefaultCredentials and CreateServiceAccountCredentialsFromDefaultPaths.
