### ISSUE TITLE
Explore using bazel for code coverage builds

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5067]
Our coverage builds usually take ~40 min. These tend to be the long poles that our PRs are blocked on before submitting. The coverage builds today use cmake (without Ninja), and run the tests one-at-a-time. We may be able to speed up the coverage builds if we switched them to use bazel because:

1. We could run the tests in parallel
2. Bazel's remote cache is more up-to-date than the ccache tarballs that we upload during the CI build and download during the PR builds

Bazel's coverage builds (i.e., `bazel coverage `) produce output in files named `coverage.dat`, which appear to be in lcov format. It looks like the codecov.io/bash script knows how to handle these files. These files would live in `cmake-out/home/*coverage/.cache/..../coverage.dat`. 

I'm not sure if this would work, whether codecov.io would understand the output correctly (probably??), or whether it would be any faster.... but it may be worth a try.

FTR: I have a small experiment PR for this at https://github.com/googleapis/google-cloud-cpp/pull/5065

**Comment by coryan** [comment]
> We could run the tests in parallel

Note that CMake can also run tests in parallel. We explicitly disable that because running coverage tests in parallel can corrupt the data:

https://stackoverflow.com/questions/14643589/code-coverage-using-gcov-on-parallel-run

We tried that before in #3530.   It is certainly possible (I would think likely) that Bazel has solved this problem better than our earlier attempts.

As you test these changes: think about coverage build and caching, if a test does not run, would this use previously cached coverage results?  Did your testing verify the effect of reducing code coverage with caching?  Did your testing verify the effect of increasing code coverage with caching?

**Comment by devjgm** [comment]
> 
> As you test these changes: think about coverage build and caching, if a test does not run, would this use previously cached coverage results? Did your testing verify the effect of reducing code coverage with caching? Did your testing verify the effect of increasing code coverage with caching?

If a test is not run due to a cache hit, it'll reuse the cached `coverage.dat` file. The output in the logs look like:

```
//google/cloud/testing_util:status_matchers_test                (cached) PASSED in 0.4s
  /h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/testing_util/status_matchers_test/coverage.dat
```

So, I believe a cache hit will look exactly the same as no cache hit from a code coverage perspective.
