### ISSUE TITLE
storage::RawClient member functions should return kUnimplemented

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5339]
We think pure virtual functions are a recipe to break backwards compatibility as we add member functions. The class should:

- Return a status of `kUnimplemented` for simpler RPCs.
- Return a satisfied future with a status of `kUnimplemented` for asynchronous and polling RPCs.
- Return a range containing a single value with status `kUnimplemented` for iteration APIs.

**Comment by remyabel** [comment]
What should be done about `virtual ClientOptions const& client_options() const = 0;` when `ClientOptions` has an explicit constructor? Do we just return `CreateDefaultClientOptions()`?

**Comment by coryan** [comment]
Good question.  Short answer is I don't know. We would probably design the class differently these days.

One possibility is to throw an exception via `google::cloud::Throw*`, that will crash with exceptions disabled, not great, but easy to explain.

Another possibility is to leave this always pure virtual, which is ugly because one function would be pure virtual and the others would not.

I think I like the second one better. /cc @devjgm in case he has better ideas.

**Comment by devjgm** [comment]
For anyone following along, the code we're talking about is here

https://github.com/googleapis/google-cloud-cpp/blob/f9d9b2498d30f83a84f206e71c3dcb721ee00d3f/google/cloud/storage/internal/raw_client.h#L53

Good question @remyabel. I don't have any better ideas. I think my vote would be to agree with @coryan 's inclination and leave that one method pure. Yes, it's a little strange that the one method is pure and all the others have a default implementation. However, that method looks different than the others since it doesn't return a `StatusOr` anyway, so it doesn't bother my aesthetic sensibilities too much.

**Comment by mr-salty** [comment]
do we think this class should be concrete or abstract? I think the latter, and making the destructor pure-virtual would be breaking at this point, so leaving this pure also solves that problem.

The real thing we're trying to accomplish is avoid breaking changes when we add methods, making the existing ones non-pure is basically an optional thing for consistency, so I don't think it's a problem. Removing a method is always going to be breaking.

**Comment by remyabel** [comment]
@mr-salty do you mind elaborating on what changes you want to see (or don't want to see)?

**Comment by devjgm** [comment]
Keeping open, but can't commit to it right now.

**Comment by coryan** [comment]
Closing, we just need to make new functions non-pure virtual.
