### ISSUE TITLE
Investigate posting relevant static and dynamic analysis findings as PR comments

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#55]
It should be possible to use the github APIs to post some of the errors from our builds directly as PR comments, for example:

* The code formatting errors have line numbers and can be flagged as comments in the PR.
* Any clang-tidy errors (in a future clang-tidy build) have line numbers and can be flagged as comments in the PR.
* The errors from the sanitizers often have line numbers and could be posted to the review too.

**Comment by devjgm** [comment]
Internal and external users have access to view build logs. We now even have a bot that posts a PR comment w/ links to the build logs. Scanning for errors in the logs and surfacing those as PR comments seems possibly nice, but I'd say probably not worth the effort since it's pretty easy to click on the log and see the _complete_ error in context.

Given the age of this issue and that we haven't really needed it yet, I think it's probably not worth keeping open. Closing to clean things up a bit.
