### ISSUE TITLE
Use absl threading classes in the project

### ISSUE THREAD

**Issue by PeteyPii** [googleapis/google-cloud-cpp#5634]
**What component of `google-cloud-cpp` is this feature request for?**
The whole project.

**Is your feature request related to a problem? Please describe.**
std::mutex and other std namespace threading classes do not play well with Google's internal user space threading library. 

**Describe the solution you'd like**
Replace std::mutex with absl::Mutex and replace other std namespace classes with absl alternatives.

**Comment by coryan** [comment]
Before making such a change, somebody needs to figure out if (a) `absl::Mutex` and friends work well with `std::mutex` with respect to [priority inversion](https://en.wikipedia.org/wiki/Priority_inversion), and (b) in case they don't, we need to warn application developers about it.

**Comment by devjgm** [comment]
@coryan can you say more about what we need to do to figure out the answer to your question above about priority inversion? Can you suggest a test or experiment we could do? Or who we'd need to ask to figure it out. I suspect the answer is "yes, it works fine", but I have not data to support that.

**Comment by devjgm** [comment]
@derekmauro can you comment at all on @coryan 's last post? In particular, do we know anything about how `absl::Mutex` works in a process that's also using `std::mutex`?

**Comment by derekmauro** [comment]
Very good question. I think @dvyukov could probably give you a better answer, but I can tell you what I know.

`absl::Mutex` is priority-aware. I'm skeptical about how well this code is battle tested as setting thread priorities is very rare in Google production code (as far as I know). There was a change to this code in the last year, which suggests there are at least some users that care about it.

I don't think we have any experience mixing `absl::Mutex` with `std::mutex` while using thread priorities, since `std::mutex` is banned in production code.

The other thing to note is that priority-awareness code in `absl::Mutex` is POSIX-only as it uses `pthread_(get|set)schedparam(3)`, but it doesn't look like it would be too hard add Windows support.

**Comment by devjgm** [comment]
What guarantees does `std::mutex` make around priority inversions? I want to make sure we're not holding Abseil to a stronger guarantee than we currently get. The answer may be UB or implementation defined based on platform and standard library implementation.

**Comment by coryan** [comment]
> What guarantees does `std::mutex` make around priority inversions?

Since C++ does not have priorities for its threads, I am sure the answer is "C++ makes no guarantees on priority inversions", it does not even talk about them.

> I want to make sure we're not holding Abseil to a stronger guarantee than we currently get.

Sure.

> The answer may be UB or implementation defined based on platform and standard library implementation.

The behavior of `std::mutex` in the presence of thread priorities is obviously implementation defined, and even then, many implementations do not bother to "define" their behavior.

Not sure how this changes anything.  If we decide to use `absl::Mutex` and we believed it does not have good priority inheritance (or another priority inversion avoidance protocol), then we should just document that.

**Comment by devjgm** [comment]
One piece of documentation we have is from https://github.com/abseil/abseil-cpp/blob/8c800bb08d353c73d7dd68538388cf3bd2bcc6d0/absl/synchronization/mutex.h#L114-L116

> // `Mutex` is not guaranteed to be "fair" in prioritizing waiting threads; it
// is, however, approximately fair over long periods, and starvation-free for
// threads at the same priority.

**Comment by derekmauro** [comment]
I just took a look at the internal [go/mutex](http://go/mutex) document and it very clearly says that it does not handle priority inversion. We should probably update `mutex.h` and even consider publishing the document.

**Comment by devjgm** [comment]
@coryan I think we should probably close this. WDYT?

**Comment by coryan** [comment]
I agree, closing.
