### ISSUE TITLE
Cleanup `std::move()` of `const` values

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6060]
This may indicate we are trying to optimize something that cannot be optimized.

https://github.com/googleapis/google-cloud-cpp/blob/fcbbc055d3100b67096857f4fae9ee09aa700c79/google/cloud/storage/parallel_upload.h#L936

https://github.com/googleapis/google-cloud-cpp/blob/fcbbc055d3100b67096857f4fae9ee09aa700c79/google/cloud/iam_bindings.h#L48

https://github.com/googleapis/google-cloud-cpp/blob/fcbbc055d3100b67096857f4fae9ee09aa700c79/google/cloud/storage/parallel_upload.h#L757

https://github.com/googleapis/google-cloud-cpp/blob/fcbbc055d3100b67096857f4fae9ee09aa700c79/google/cloud/storage/parallel_upload.h#L802

https://github.com/googleapis/google-cloud-cpp/blob/fcbbc055d3100b67096857f4fae9ee09aa700c79/google/cloud/storage/parallel_upload.h#L684

**Comment by devjgm** [comment]
We disable

https://github.com/googleapis/google-cloud-cpp/blob/912f4a396d3f4f8cd7d7ad4b978bbe364f9aabbc/.clang-tidy#L21-L26

Is something warning about these?

**Comment by coryan** [comment]
> Is something warning about these?

Yes, see the internal email thread.

This is different (I think) from the `clang-tidy` warning.  The function is holding a `Foo const&` and then passing it to another function via `std::move()`.  That might be the right thing to do (say because you want to signal that you are no longer going to use the thing), but also might be an attempt to move the object, but that is not what happens.

**Comment by remyabel** [comment]
Is there an existing document on when it's appropriate to use `std::move` in this codebase?

**Comment by devjgm** [comment]
@remyabel we don't have a document like that, but it's possible one would be helpful. I've personally considered when-to-move to be more of a black-and-white (and simpler) issue than some checkers do.

In my mind, I think reasoning about about when to `move` should be able to be done locally _at the call site_, without having to care about the _implementation detail_ about how a function chooses to accept its parameter or the type of the moved object. I use the following two principles that _I think_ always work and result in correct and the most efficient move-related code (someone please tell me if I'm wrong):

1. Using a moved-from object is always wrong and always a bug. I'd love a check that flagged these cases correctly. [bugprone-use-after-move](https://clang.llvm.org/extra/clang-tidy/checks/bugprone-use-after-move.html) catches some of these.
2. Moving any object when you're done with it should always be OK, regardless of the object's type or the argument type being moved into.

I consider warnings about instances of case (2) to be false positives.

@coryan IMO, I think these warnings are false positives and eliminating the move here does not seem like an improvement to me.

> but also might be an attempt to move the object, but that is not what happens

I see that concern, but I think it doesn't matter, and I can't conceive of a bug resulting from that. I think the "bug" is programmers thinking that `std::move()` means move (well, maybe the bug was the standards committing naming a cast "move"). `std::move(a)` doesn't mean that `a` will be moved, because maybe `A` doesn't have a move-constructor, or maybe `using A = int`, or maybe `a` is a `const&` (as in the flagged warnings here). In all those cases, I think it's an implementation that the caller does not need to be concerned with. And _if_ the programmer follows the two simple principles I suggest above, then the code will be correct and efficient even if/when `A` changes from a const-ref to a value, or if the function A is being passed to starts accepting `A` by value, etc.

IMO, I think the code in question in the first post is _more robust_ as written _with_ the `std::move`, and changing things because of the warning would fix zero bugs and make the code slightly less robust against future modifications and maintenance.

**Comment by coryan** [comment]
> @coryan IMO, I think these warnings are false positives and eliminating the move here does not seem like an improvement to me.

I do not think that eliminating the move is (necessarily) the right fix, nor was I planning to.  In some cases making the object non-const is the right fix.  A good example is:

https://github.com/googleapis/google-cloud-cpp/blob/fcbbc055d3100b67096857f4fae9ee09aa700c79/google/cloud/storage/parallel_upload.h#L684

`sources` is the lambda's argument, which is declared `std::vector<std::string> const& sources`, I think it should be `std::vector<std::string> sources`.  The lambda is used through a `std::function<void(std::vector<std::string>)>`, and it is sent to something that consumes the vector, so really it should be moving and avoiding the copies (not multiplying them).

**Comment by devjgm** [comment]
That's a good point and example. Agreed.

**Comment by coryan** [comment]
I think these are all fixed.
