### ISSUE TITLE
Consider removing ".gcpcxx.pb" from generated file names

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6074]
This is a discussion that we started internally, but I'm moving it to an issue so we don't forget.

I think we probably want to remove the `.gcpcxx.pb` component from autogenerated source files, because it adds noise and an implementation detail that our customers need not be concerned with. As far as our customers are concerned, our C++ libraries are checked in C++ source files, that are all intended directly for customers to read and use. Whether we happen to hand-write a particular file or autogenerate it is an implementation detail that the customer should not care about. Absent a _customer benefit_ from including `.gcpcxx.pb` in path names, I think we should keep things simpler and remove that component.

It's possible that it may benefit _us_ to be able to distinguish generated files from hand-written ones. But again, I'd say that this is an implementation detail that we should shield customers from. We don't have use use the pathname as the indicator for this since the generated files already have comments, we could use something like `grep -rl "Generated by the Codegen C++ plugin"`

I'm not the expert on the generator, but it looks like changing this should be relatively straight forward since this component has already been nicely factored out into its own function:

https://github.com/googleapis/google-cloud-cpp/blob/055f7a35f3acf0025652135d3368a69c3a843e03/generator/internal/codegen_utils.cc#L42

Changing that, plus a few `git mv`s, and I'd imagine that's about it.

I'd be curious to hear if there are good reasons to keep this path component that I've overlooked. Otherwise, we probably want to remove it.

/cc: @scotthart for comments, as the expert on the generator

**Comment by devjgm** [comment]
@scotthart is this a lot of work? Or is this difficult to change? If not, I think we do want to make this change before we GA any generated libraries.

WDYT?

**Comment by scotthart** [comment]
I don't think it's particularly burdensome for customers to have the specialized filenames as includes. More than likely, they already have to include pb.h files for the types they used that are defined in .proto files.

Furthermore, when the community wants to contribute changes to this repo, having the gcpcxx.pb file suffix is a clear indicator that spending time making a PR with changes to those files would be a waste of time as they are generated files. The presence of the extra suffix clearly differentiates them from files in our other libraries that are not generated and can be modified directly with a PR. 

While we do add some verbiage to the top of file boilerplate indicating the contents are generated, such comments can be overlooked. Having the extra suffix in the filename is, in effect, required reading.

While we know exactly which libraries are generated vs. handwritten, contributors who only use 1 or 2 libraries may not. I would hate to frustrate contributors them by having to decline their PR because they made a lot of changes in the wrong places.

**Comment by devjgm** [comment]
While I agree that the `.gcpcxx.pb` naming is not too burdensome, I think it would be better for our customers if it were not there. Whether customers already deal w/ `pb.h` or not does not sway my mind because I think we can do better in this case (and that is a different situation anyway, because the _customer_ runs a tool to convert `.proto` -> `.pb.h`, which is not the case here).

I agree that the verbose naming may be beneficial to us and potential contributors. However, I don't think that's the right audience to optimize for. We need to optimize for our _users_ who will vastly outnumber our contributors (hopefully!). And for our _users_, it does not matter whether a file is generated by us or tool. The fact that we used a tool to generate some of the source files is completely an implementation detail to customers.

I see some negatives for our customers with the `.gcpcxx.pb` noise in our file names, and I see zero advantages for our customers. I think we should remove the `.gcpcxx.pb` part of our generated file names.

**Comment by MrMoose** [comment]
For what it's worth, I am a new user of the c++ sdk library and I can offer my point of view:

Personally I couldn't care less about how the cpp or hpp files the library is composed of are named. As long as they are not exposed to me. I have seen includes containing `.gcpcxx.pb` and as soon as I do, I am immediately certain I am looking at the wrong place and I am not supposed to include them at all. I feel like I'm doing the wrong thing as I also consider them implementation detail.

**Comment by devjgm** [comment]
Thanks for the feedback @MrMoose. We agree. We discussed this as a team yesterday and agreed that it was best to remove `.gcpcxx.pb` from our user-facing headers. That will likely happen soon-ish, and it _would_ be a breaking change if a user were including files by their old name.
