### ISSUE TITLE
Consider "bazel sync" instead of "bazel fetch"

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6140]
We use `bazel fetch` in our (Bazel) CI builds to prevent flakes caused by failed downloads.  It seems like we could simplify this by using `bazel sync` instead. `fetch` requires listing the rules that will be executed, and some indirect dependencies.  `sync` seems to download things we do not need, e.g., the SDKs for Windows when compiling on Linux.

**Comment by devjgm** [comment]
I think we want to keep `bazel fetch` not `bazel sync`. The later downloads more deps than are necessary. However, I think we can simplify our bazel fetch invocation from

https://github.com/googleapis/google-cloud-cpp/blob/a6329c16e474fe19f0d873d67eed408b26785cc5/ci/cloudbuild/builds/lib/bazel.sh#L42-L47

To simply `bazel fetch ...`.

I think the simpler invocation is supposed to download all the deps that are necessary. And in an experiment on my local machine, it appeared to do just that. I did a clean `bazel build ...`, and looked at all the files downloaded in `~/.cache/bazel/_bazel_jgm/cache/repos/`. Then I expunged everything and did a `bazel fetch ...`, and it fetched everything that the bazel build fetched.

**Comment by devjgm** [comment]
Well, I just found https://github.com/googleapis/google-cloud-cpp/pull/5346, which seems to suggest that I'm wrong... let me do a bit more investigation.

**Comment by devjgm** [comment]
I think we _should_ be able to only specify `bazel fetch ...` and have it get everything, but the PR above is correct that we need to list more. I think that's a bazel bug and filed: https://github.com/bazelbuild/bazel/issues/13847.

Regardless, for the purpose of _this_ issue, we want to keep `bazel fetch`. `bazel sync` is not what we want because it fetches way too much.
