### ISSUE TITLE
check_gcp_environment.cc:60] BIOS data file cannot be opened.

### ISSUE THREAD

**Issue by SimonHausdorf** [googleapis/google-cloud-cpp#6300]
**Does this issue affect the google-cloud-cpp project?**
yes

**What component of `google-cloud-cpp` is this related to?**
I am using pubusb but I think it's a general problem

**Describe the bug**
I am receiving the following error `E0421 08:37:58.704957838      66 check_gcp_environment.cc:60] BIOS data file cannot be opened.` when launching my application. gRPC is trying to open the file `/sys/class/dmi/id/product_name` which does not exist in my filesystem. I am running a docker container on GCE. It seems like it was changed to INFO here https://github.com/grpc/grpc/pull/24893/files however I believe that google-cloud-cpp is using an older version on gRPC?
I think that the error is linked to the fact that I am building it inside docker?

**To Reproduce**
1. Include google-cloud-cpp via vcpkg
2. build a docker image and compile the code
3. run your application

**Expected behavior**
Error should be info and not cause a crash

**Operating system:**
Docker with ubuntu 21.04

**What version of `google-cloud-cpp` are you using?**
installed package from vcpkg

**Comment by coryan** [comment]
Thanks for the detailed bug report.

> **Describe the bug**
> I am receiving the following error `E0421 08:37:58.704957838 66 check_gcp_environment.cc:60] BIOS data file cannot be opened.` when launching my application. gRPC is trying to open the file `/sys/class/dmi/id/product_name` which does not exist in my filesystem. I am running a docker container on GCE. It seems like it was changed to INFO here https://github.com/grpc/grpc/pull/24893/files

That was merged in 2020-12-03, and should appear in the 1.35.x, 1.36.x and 1.37.x series.

> however I believe that google-cloud-cpp is using an older version on gRPC?

We test and link against multiple different versions.  I think this is a packaging problem for gRPC.

> I think that the error is linked to the fact that I am building it inside docker?
> **What version of `google-cloud-cpp` are you using?**
> installed package from vcpkg

Okay, vcpkg has not updated gRPC since 1.33.1:

https://github.com/microsoft/vcpkg/blob/master/ports/grpc/portfile.cmake

There are a number of bugs and pending PRs to get that fixed:

https://github.com/microsoft/vcpkg/pull/15078
https://github.com/microsoft/vcpkg/pull/17151
https://github.com/microsoft/vcpkg/pull/17276

It seems like it is all tangled up with updating `upb` and updating the patches for UWP and other windows variants.

I can think of two ways to get you unblocked:

* You can create a [vcpkg overlay](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) for a newer version of gRPC.  That might seem daunting, but for Linux I expect you could skip most of the patches.
* Meanwhile, I will try to see if I can help move those gRPC PRs along, no promises though, all I can do is volunteer to help, but there are multiple other folks to decide.

**Comment by coryan** [comment]
Changing the type because I do not see this as a problem in `google-cloud-cpp` per-se.

**Comment by coryan** [comment]
The nice folks from vcpkg have updated gRPC:

https://github.com/microsoft/vcpkg/pull/17422

I think that should fix this issue, please feel free to reopen if it does not.
