### ISSUE TITLE
[Flake] Error preparing docker image for GCB

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6327]
Maybe a race condition?  Or could be a bug in Koniko?

https://pantheon.corp.google.com/cloud-build/builds/a3f20e65-2048-4a59-9a97-f81f608b344a?project=cloud-cpp-testing-resources

**Comment by devjgm** [comment]
```
error pushing image: failed to push to destination gcr.io/cloud-cpp-testing-resources/cloudbuild/fedora:a3f20e65-2048-4a59-9a97-f81f608b344a: PATCH https://gcr.io/v2/cloud-cpp-testing-resources/cloudbuild/fedora/blobs/uploads/AJAD5v0Kmaa97Q7eSqRBWNCBtHaqgtgUTHrARVmCjiX7qi4ddTPeXG0WbpDET60B-1S4Bj3pqCLax2oebsCuMVM: UNKNOWN: Unable to determine the upload's size.
```

**Comment by coryan** [comment]
Maybe this can help:

https://github.com/GoogleContainerTools/kaniko/blob/master/README.md#--push-retry

**Comment by devjgm** [comment]
Interesting. The kaniko image we're using is `gcr.io/kaniko-project/executor:edge`, which is from last year (May 7, 2020). There are many version updates since then.

Do you know why we're using the `:edge` tag? I'm thinking that maybe updating to a newer version of kaniko may fix the issue (and maybe adding that `--push-retry` flag may help too)

**Comment by devjgm** [comment]
fwiw, it turns out that newer version of a Kaniko seem to SEGV, for a reason I don't understand but I filed a bug about a couple months ago: https://github.com/GoogleContainerTools/kaniko/issues/1604

**Comment by coryan** [comment]
My recollection is that I tried to use `:latest` that had some bugs with (maybe) multi-stage Dockerfiles, I switched to `:edge` and never changed the tag.  This is all very depressing.
