### ISSUE TITLE
Consider removing the cmake-super build

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6424]
We've talked several times about removing the cmake-super build and "dropping support for" super builds (quoted because I'm not completely sure what our support here means). I didn't see an issue for this, so I'm creating one.

I think we should:

1. Describe the value of the super build (just in this issue, for ourselves). Why do we have it? Do our customers need it? Do our customers have an alternative?
2. Do we plan to stop supporting super builds completely, or just stop running our CI test?
3. Would we replace the super build with something? Maybe a vcpkg manifest build? Would that solve all the customer needs that super builds do?

We should also note that our mac (and windows?) builds use the super build, so that would need to be replaced with something else.

So this is just a place for us to record our thoughts and keep track of this.

**Comment by coryan** [comment]
Thank you for doing this.

> Why do we have it?

Historical reasons that (I believe) no longer apply:

- To test that customers could use `google-cloud-cpp` as part of a larger super build (this was needed when `google-cloud-cpp` supported both submodules and "external" dependencies, like gRPC does).
- Over time, I have grown convinced that this test is unnecessary: a super build is just like any other build, the dependencies are installed first by "something" (CMake, vcpkg, a user, some package manager) and we just use those deps.
- Historically, it was a convenient way to install the deps in $HOME.  vcpkg is now better for that purpose.
- We used it for CIs on macOS because I could not figure out a better way to install deps there.  

> Do our customers need it?

I do not think so.  They *may* be using it, e.g., their own super build can download `google-cloud-cpp` and then configure it using `cmake -Ssuper -B ...` (or its equivalent).

> Do our customers have an alternative?

Yes, they can use vcpkg.  They can copy the `super/*.cmake` files into their own super build.

> Do we plan to stop supporting super builds completely, or just stop running our CI test?

I think we should always support customer *using* `google-cloud-cpp` in a larger super build.  I do not think we need to have our own dedicated super builds to test that because our CMake files are not that special (not anymore).

> Would we replace the super build with something?

No, I do not think we need to do this.

> Maybe a vcpkg manifest build?

That would be a convenient way for us to run CI builds that need to install deps, yes, but I do not think we need to tell customers that this is their only choice.

> Would that solve all the customer needs that super builds do?

Yes `vcpkg` solves a similar problem. But I think our `CMake` files work fine (and will continue to work fine) as part of a larger super build as long as we continue to (a) test with `vcpkg` (which we do a lot), (b) avoid `git submodules`, (c) test with all the dependencies pre-installed (like the `demo-*` builds do).  A dedicated super build test is redundant in that case.

**Comment by devjgm** [comment]
OK, thanks for all those answers. Here's what I'm thinking the next steps probably should be:

- [ ] We need to change the macos build(s) to use vcpkg first.
- [ ] Once that's done, I think we can remove the super build and the `super/...` directory.
- [ ] We should include an announcement about it in our `CHANGELOG.md`, even directing what users could do instead, but I don't think we need to wait after the announcement.

**Comment by devjgm** [comment]
Actually, I just noticed https://github.com/googleapis/google-cloud-cpp/commit/aa63bb6eb58560506f43f991179e6f716c29f092, and the message it displays to users is 

> CMake Warning at ExternalProjectHelper.cmake:20 (message):
    Super builds are no longer recommended, and will be removed on 2022-05-01
    or shortly after.  If you want to automatically download and build the
    `google-cloud-cpp` dependencies we recommend that you use `vcpkg` as
    described in /doc/contributor/howto-guide-setup-cmake-environment.md

So according to that message, we should keep `super/` until May 2022.

**Comment by coryan** [comment]
Ugh. My bad.  We can still simplify things by **not** using super builds, except in one GCB build?

**Comment by coryan** [comment]
Couple of data points: we have not (yet) cut a release with that warning in it, and the warning only appears if you use our helper, which really, nobody can use in a super build.  I guess it is not too late to change our minds about this.

**Comment by devjgm** [comment]
Ahh. Cool. Just removing that date from the warning would give us some flexibility.

**Comment by devjgm** [comment]
Builds that use `super/`
* macos:cmake-super
* gcb:gcc-54
* gcb:clang-38
* gcb:cmake-super

**Comment by coryan** [comment]
Just a note, we can close #3930 and #4044 if we just remove the super builds.

**Comment by devjgm** [comment]
Bummer. `vcpkg` requires [gcc >= 6.0](https://github.com/microsoft/vcpkg-tool/blob/74c95caade9143ca166dbd49fbd2a0d740fd3d1f/cmake/utilities.cmake#L6). Also the installed libstdc++ library isn't properly detected and appears to be too old too.

**Comment by coryan** [comment]
Ugh.  We could compile all the dependencies, like we do in the `fedora-34.Dockerfile`.
