### ISSUE TITLE
[macos] build.sh error: Error: Unknown command: cask

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6440]
Output from `build.sh` with `-x`

```shell
2021-05-03T15:57:23Z: Update or reinstall 'google-cloud-sdk'.
+ brew --version
Homebrew 3.1.5
Homebrew/homebrew-core (git revision 1fc4222cac; last commit 2021-05-03)
+ env HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall google-cloud-sdk
Error: No available formula or cask with the name "google-cloud-sdk".
+ env HOMEBREW_NO_AUTO_UPDATE=1 brew cask install google-cloud-sdk
Error: Unknown command: cask
+ true
+ env HOMEBREW_NO_AUTO_UPDATE=1 brew doctor
Your system is ready to brew.
```

The code is here:

https://github.com/googleapis/google-cloud-cpp/blob/2126221769686d0ec3524f41ed5737d66729a018/ci/kokoro/macos/build.sh#L64-L67

Should the command be `brew install --cask google-cloud-sdk` ?

I changed to this, and it seemed to work. However, when I re-ran the build, when it was reinstalling this, I was prompted for my password so it could remove the old files and re-install them:

```
==> Downloading https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
Already downloaded: /Users/jgm/Library/Caches/Homebrew/downloads/cda39f18c3069c1a4ac0cd5b1d91541af945cd331eba8443c58ec5c890343c0a--google-cloud-sdk.tar.gz
Warning: No checksum defined for cask 'google-cloud-sdk', skipping verification.
All formula dependencies satisfied.
==> Uninstalling Cask google-cloud-sdk
==> Removing files:
/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk
Password:
Sorry, try again.
Password:
==> Purging files for version latest of Cask google-cloud-sdk
```

*Question*: Why are we re-installing this?

**Comment by coryan** [comment]
> Should the command be `brew install --cask google-cloud-sdk` ?

Maybe.  As I remember, the version of `brew` in the CI machines did not support that.  Or maybe it did not work in the old pool of machines and works in the new pool, and for a short while we were using both.

> _Question_: Why are we re-installing this?

Because when I tried to move our builds to the `catalina` pool some of the machines had a broken `google-cloud-sdk` installed.  As in: it would be there, but if you try to run it it would crash.  But if it is a drag maybe just enable these reinstalls on CI machines?

Or just remove all of it and see how it works in the CI machines, I may have just hacked stuff until it worked, but may not be the cleanest approach.
