### ISSUE TITLE
Improvement ideas for `google::cloud::Log*`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#662]
These are ideas to make the logging classes better:

- [x] Implement a `LogBackend` that keeps the last N messages in memory, and only if a sufficiently severe message is generated then the last N messages are dump to another `LogBackend`.
- [ ] Add a GCP_LOG_IF() macro that logs only if a condition is met.
- [ ] Add a GCP_LOG_SEV() that accepts dynamic severity levels.
- [ ] Automatically configure the `LogBackends` based on a JSON description of the hierarchy of backends. Note that we should let the application decide what is the *source* for this configuration (flags, environment variables, YAML file, whatever).
- [ ] Implement a `LogBackend` that logs directly to a file.
- [ ] Implement log rotation on log files.
- [ ] `LogBackend` for Stackdriver.
- [ ] `LogBackend` for Boost.Log
- [ ] `LogBackend` to glog.

**Comment by devbww** [comment]
#4034 (Improve logging configuration for integration tests). which was closed in lieu of this, said:

> We could enable full tracing for all the integration tests, just set GOOGLE_CLOUD_CPP_ENABLE_TRACING=cpp and GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes in the environment. This will produce a lot of output, but would be mostly hidden.

This proved infeasible ... indeed there was too much output. See #5626, #5627, and #5636.

> We could also implement a fancy logger that preserves the last N messages, and logs them only if one of them is an error or when a test assertion fails.

Keeping the last N log messages isn't too complicated, and we could certainly dump those when processing a new message of high severity.  But I don't know how to `GCP_LOG()` a high-severity log message, or otherwise dump the log-message buffer, upon a googletest failure.

**Comment by devjgm** [comment]
Discussed. Closing until we need these.
