### ISSUE TITLE
`storage::ObjectWriteStream` left in unusable state after `Suspend()` or moves

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7044]
**What component of `google-cloud-cpp` is this related to?**

Storage.

**Describe the bug**

When using an `storage::ObjectWriteStream` some operations can result in a crash, for example:

```cc
void F(gcs::Client c) {
  auto stream = c.WriteObject(...);

  std::move(stream).Suspend();
  stream.last_status(); // <-- crash
}

void G(gcs::Client c) {
  auto stream = c.WriteObject(...);

  auto os = std::move(stream); 
  stream.last_status(); // <-- crash
}
```

**Expected behavior**

The class should not crash, maybe return the last before the move-from, or maybe return `Status(StatusCode::kInvalid, ...)`.

**Comment by devjgm** [comment]
The bug is not obvious to me since both `F` and `G` use `stream` after moving it, and so a crash in that code does not immediately seem wrong.

**Comment by coryan** [comment]
I think it depends on how you read "**valid** but otherwise indeterminate state".  Is it valid that `stream.last_status()` crashes?  Maybe, it is certainly unexpected.  I was reading the spec, and then I figured "maybe ask the interwebs":

https://stackoverflow.com/questions/25690636/is-it-valid-to-construct-an-stdostream-from-a-null-buffer

Seems like it is normal for iostream to "just work" with a null streambuf.  We could define `last_status()` to behave in any way we want to.  I just think this is too surprising / unexpected.

**Comment by devjgm** [comment]
To be clear, I wasn't objecting to not crashing. I'm just making a pedantic comment that doesn't really matter much (likely I'm wasting time... sorry).

But I think the bug is actually in the caller in the example `F` and `G` functions above that use the moved-from object and assume something about it that isn't defined. A moved-from object's state is UB, and using it as more than that is bad. Unless we _define_ the moved-from state of our `stream` object above as something that continues to be usable in some way, it seems like it's still UB in the calling code, just without a crash.

Anyway, your fix LGTM.
