### ISSUE TITLE
LNK2001 linker error for google cloud storage

### ISSUE THREAD

**Issue by LSG8** [googleapis/google-cloud-cpp#7887]
I want to use bigquery table insert/update using my cpp code. So, I have installed this module. I am using visual studio 2022 and performed installation using cmake in cmd using the following lines of code of the instruction [https://github.com/googleapis/google-cloud-cpp#building-with-cmake](url)
`git -C $HOME clone https://github.com/microsoft/vcpkg.git
env VCPKG_ROOT=$HOME/vcpkg $HOME/vcpkg/bootstrap-vcpkg.sh
cmake -H. -Bcmake-out/ -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake
cmake --build cmake-out -- -j $(nproc)`

I only want to use bigquery tables. After installation, I have included
$HOME\cmake-out\vcpkg_installed\x64-windows\include
$HOME
these two directories in the c/c++ section of the project configuration properties.

Linked 
$HOME\cmake-out\vcpkg_installed\x64-windows\lib
$HOME\cmake-out
$HOME
$HOME\cmake-out\external\googleapis\google\cloud
$HOME\cmake-out\google\cloud\storage\Debug
these directories in linker.

Though not sure which .lib and .dll file I should add as 'additional dependencies' as there are a lot of those. So, didn't add any. 
Now, as per the example here [https://github.com/googleapis/google-cloud-cpp#quickstart](url), I added the following that works fine.
`#include "google/cloud/storage/client.h"`
But when I try to create the google storage client like this [auto client = google::cloud::storage::Client();](url), I get the following compiling error
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: __cdecl google::cloud::storage::v1_36_0::Client::Client(class google::cloud::v1_36_0::Options)" (??0Client@v1_36_0@storage@cloud@google@@QEAA@VOptions@134@@Z)	EQ	D:\Lahari\work\EQ\earthquake-drs\Grid.obj	1	
`
I am new to cpp and visual studio. Please guide me how to link this module properly for bigquery.

**Comment by coryan** [comment]
> Though not sure which .lib and .dll file I should add as 'additional dependencies' as there are a lot of those. So, didn't add any.

I do not think that will work.  If you are using some of the libraries in `google-cloud-cpp` you need to link at least some of them.  If you are using CMake, Make, or Bazel, as your build system there are instructions in the `quickstart/` directories for each library.  The advantage of these tools is that you can just provide your direct dependency and the tool figures out all the libraries you need.  For example, using CMake you say:

https://github.com/googleapis/google-cloud-cpp/blob/541fcb6a2afbc7cf0f3c376b2061df8ec805a8b8/google/cloud/bigquery/quickstart/CMakeLists.txt#L35

And the tool will figure out what else to link (I count about 70 such dependencies for something like BigQuery).

> I am new to cpp and visual studio.

Okay. This is a steep learning curve you are starting on.  Consider joining something like https://www.includecpp.org/discord/ There are dedicated channels to help folks getting started with C++.

It has been many years since I manually configured Visual Studio to link any libraries, I am afraid there is no much help I can offer there, but let me give you some pointers.

I noticed you are using `vcpkg` as your package manager, if that is the case, then maybe the instructions here can help:

https://vcpkg.readthedocs.io/en/latest/examples/installing-and-using-packages/#msbuild

I also understand that visual studio supports CMake-based projects:

https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170

I would guess that putting those two things together could get you a reasonable IDE + build system.

> Please guide me how to link this module properly for bigquery.

I recommend that you start by looking at the quickstart program for BigQuery:

https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/bigquery/quickstart/README.md

Note that the BigQuery library only supports the BigQuery Read API:

**Comment by coryan** [comment]
As there are no follow ups in 30 days I am going to assume your question was answered.  Please reopen this issue or start a discussion if you need additional help.
