### ISSUE TITLE
Generate library for `connectgateway.googleapis.com`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#8731]

**Comment by dbolduc** [comment]
I do not think we should generate the library at this time, because (as of writing this) there are no calls to make to the [v1 service](https://github.com/googleapis/googleapis/blob/487c2cba96ea55d866ae19b464b7e424d38e8aa4/google/cloud/gkeconnect/gateway/v1/gateway.proto#L36-L38) (There is only [v1beta1](https://github.com/googleapis/googleapis/blob/487c2cba96ea55d866ae19b464b7e424d38e8aa4/google/cloud/gkeconnect/gateway/v1beta1/gateway.proto))

Notes for when we do pick this up:
* I think this library should be called: "gkeconnectgateway". (python goes with a similar name: https://github.com/googleapis/python-gke-connect-gateway)
* [service config json](https://github.com/googleapis/googleapis/blob/487c2cba96ea55d866ae19b464b7e424d38e8aa4/google/cloud/gkeconnect/gateway/v1/connectgw_grpc_service_config.json)
* [cloud docs](https://cloud.google.com/anthos/multicluster-management/gateway)

**Comment by coryan** [comment]
Still empty service, nothing to do here.

**Comment by coryan** [comment]
Still empty service.

**Comment by coryan** [comment]
Closing until somebody creates an actual service with a GA package name.
