### ISSUE TITLE
Remove check for empty Authorization header

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#9200]
Determine root cause for calling CurlImpl::SetHeader with "authorization: ", fix it, and remove existing guard clause.

**Comment by coryan** [comment]
I think this is simply because the API for credentials is complicated.  The authorization header can be empty:

https://github.com/googleapis/google-cloud-cpp/blob/8742011a7ab847c4e9699f04c7e77b583f2a2128/google/cloud/storage/oauth2/anonymous_credentials.cc#L23-L25

In the `CurlClient` that would call `AddHeader()` with an empty string, which has no effect:

https://github.com/googleapis/google-cloud-cpp/blob/8742011a7ab847c4e9699f04c7e77b583f2a2128/google/cloud/storage/internal/curl_client.cc#L133

In the `RestClient` that would add `Authorization: `:

https://github.com/googleapis/google-cloud-cpp/blob/8742011a7ab847c4e9699f04c7e77b583f2a2128/google/cloud/storage/internal/rest_client.cc#L117-L118

**Comment by coryan** [comment]
Closing, can reopen if it is ever a problem.
